### ISSUE TITLE
The remote host "waldevdbclnxtst06.dev.rocketsoftware.com" was not found. 

### ISSUE THREAD

**Issue by Regis111** [ibmdb/node-ibm_db#1002]
When running tests in ibm_db package, I get error:
```
[Error: [IBM][CLI Driver] SQL1336N  The remote host "waldevdbclnxtst06.dev.rocketsoftware.com" was not found.  SQLSTATE=08001
] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -1336,
  state: '08001'
}
```

Steps to Reproduce:

1. cd `node_modules/ibm_db/test/`
2. `node run-tests.js`

# Please provide below information while opening an issue to understand your problem

- Operating System Name where ibm_db is installed:
`v20.11.0`
- Target Db2 Server Version or output of `db2level` command from Db2 database system:

### For non-Windows system, output of below commands from terminal:
  uname - `Linux`
  uname -m - `x86_64`
  node -v - `v20.11.0`

  npm ls ibm_db: version used is "3.2.4"

  db2level: 
```
DB21085I  This instance or install (instance name, where applicable: "regis") 
uses "64" bits and DB2 code release "SQL11059" with level identifier 
"060A010F".
Informational tokens are "DB2 v11.5.9.0", "s2310270807", "DYN2310270807AMD64", 
and Fix Pack "0".
Product is installed at "/home/regis/sqllib".
```
  echo $IBM_DB_HOME: `/home/regis/sqllib`

  echo $PATH: blank
  echo $LD_LIBRARY_PATH $DYLD_LIBRARY_PATH
```
/home/regis/sqllib/lib64:/home/regis/sqllib/lib64/gskit:/home/regis/sqllib/lib32
```

**Comment by bimalkjha** [comment]
@Regis111 Before running test file from `ibm_db\test` directory, you need to update database connection information in `ibm_db\test\config.json` file. waldevdbclnxtst06 is used as dummy value in config.json file and since you have not updated it, it is using the dummy value and hence the error.
If you do not want to update config.json, you can set environment variable IBM_DB_HOSTNAME as used here: https://github.com/ibmdb/node-ibm_db/blob/master/test/common.js#L70C43-L70C58

If you still have issue, please share the test file that you are executing and what connection string you are using. Thanks.
