### ISSUE TITLE
Connection Pooling and OPTIONS

### ISSUE THREAD

**Issue by Chandragandla** [ibmdb/node-ibm_db#112]
Please clarify below.

1) Please let us know if the module has the support for setting the max and min connections.
If not, what's the best approach to limit the connections opened from the pool?
2) DB object takes OPTIONS as an argument to avoid re-loading of the native odbc libraries,
is there a documentation for what needs to passed in OPTIONS?

Thanks

**Comment by bimalkjha** [comment]
1. There is no restriction on maximum number of connection from ibm_db. Restriction is at server side based on MAX_CONNECTIONS db cfg.
Since, ibm_db uses ODBC/CLI driver internally, so the restrictions of CLI driver will apply here.

The pool will keep growing automatically if there is no available connection to return, until CLI driver gives successful connection to node-ibm_db driver. I don't see any restriction from coding side. Hope, it clarifies.

2. Options can be used to pass previously allocated odbc instance, fetchMode and connectTimeout. Please check the Database() function definition for more info: https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L98
