### ISSUE TITLE
issues while fetching blob as pdf

### ISSUE THREAD

**Issue by vikram216** [ibmdb/node-ibm_db#135]
I have a pdf document stored in one db2 table as BLOB. I tried the following code to fetch the BLOB and store it as pdf on my local machine. Everything works fine but the pdf comes out as corrupted pdf and is of no use.

`var Promise = require('bluebird');
var fs = require('fs');
var using = Promise.using;
var connectionPool = require('./db/connectionPool2');
using(connectionPool.getSqlConnection(), function(connection) {
        return connection.queryAsync("select BLOBCOLUMN FROM MYSCHEMA.MYTABLEWHERE PARTKEY=1234");
			connection.close();
    }).spread(function(rows,fields) {
    		rows.forEach(function(row){ 
    				var data = new Buffer(row.BLOBCOLUMN);
    				fs.writeFile("./mypdf.pdf", data, function(err) {
    					if(err) {
     					   return console.log(err);
    							}

   						 console.log("The file was saved!");
						}); 

    			});

    }).error(function(err) {
        console.log('[Log GET DOCUMENT DATA FAILED] := ' + err);
    });`

**Comment by rhtpandeyIN** [comment]
Hi @vikram216, It seems the issue of storing selected data as Buffer. 
`
var data = new Buffer(row.BLOBCOLUMN);
fs.writeFile("./mypdf.pdf", data, function(err) 
`
don't save the data into Buffer after selection, just write it direct into the file with 'hex' conversion.
please refer below working code.
 
`
var path = require('path');
var Promise = require('bluebird');
var fs = require('fs');
var using = Promise.using;
var connectionPool = require('./db/connectionPool2');
//var ibmdb = require('ibm_db');

using(connectionPool.getSqlConnection(), function(connection) {
        return connection.queryAsync("select BLOBCOLUMN FROM MYSCHEMA.MYTABLE WHERE PARTKEY=1234");
			connection.close();
			
    }).spread(function(rows,fields) {
    		rows.forEach(function(row){ 
    				//var data = new Buffer(row.BLOBCOLUMN);
    				fs.writeFile("./mypdf.pdf", row.BLOBCOLUMN, 'hex', function(err) {
    					if(err) {
     					   return console.log(err);
    							}

   						 console.log("The file was saved!");
						}); 

    			});

    }).error(function(err) {
        console.log('[Log GET DOCUMENT DATA FAILED] := ' + err);
    });
`

Thank you for letting us know about this issue and warm regards for your efforts which helped us to track down the root cause.
Please contact if you facing same problem again.

**Comment by vikram216** [comment]
Great!! This is working fine. Thanks a lot for your help
