### ISSUE TITLE
Application crashing when uploading and download files

### ISSUE THREAD

**Issue by dhaazen** [ibmdb/node-ibm_db#141]
Hello,

I'm seeing inconsistent errors when uploading and downloading documents. An error will be thrown and the application will immediately crash.

Some errors below:

```
node: ../src/odbc.cpp:620: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != -2' failed.
```
```
ERR *** Error in `node': malloc(): memory corruption: 0x0000000002584130 ***
```
```
ERR *** Error in `node': free(): invalid next size (normal): 0x0000000002df64b0 ***
```
```
ERR *** Error in `node': double free or corruption (!prev): 0x00000000034e67e0 ***
```

immediately after the error I'll get:

```
ERR Aborted (core dumped)
```

and the application will reboot

It seems to be an error relating to the odbc which I know is used by node-ibm_db. Unfortunately the errors are inconsistent. But when they occur the result is severe. Please advise.

**Comment by bimalkjha** [comment]
Please share the node.js version being used here. Thanks.

**Comment by bimalkjha** [comment]
Since you are able to repro the issue locally out of the bluemix, can you try to insert and select same file using ibm_db/test/test-blob-insert.js script? Thanks.

**Comment by dhaazen** [comment]
@bimalkjha Node version v4.2 on Bluemix and v4.4 locally (yeah know I should have them synchronized)

**Comment by bimalkjha** [comment]
@dhaazen could you please take the latest code using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` and check.

If issue still exist, then collect the logs using below steps and share the traces:
Update db2cli.ini file as suggested before with Trace=1 and tracefilename=clitrc.txt. Then run below commands:
```
export IBM_DB_HOME=<path_to_ibm_db>/installer/clidriver
export PATH=$IBM_DB_HOME/bin:$IBM_DB_HOME/adm:$IBM_DB_HOME/lib:$PATH
export DYLD_LIBRARY_PATH=$IBM_DB_HOME/lib:$DYLD_LIBRARY_PATH
db2trc on -l 2m
```
Now run your app to repro the issue. Immediately after repro, run below commands:
```
db2trc dump 1.trc
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
```
Now share the clitrc.txt, 1.flw and 1.fmt file with us. Thanks.

**Comment by dhaazen** [comment]
Hey @bimalkjha,

I ran into the issue again different but similar error down below:

```
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 27:1
Assertion failed: (ret != SQL_INVALID_HANDLE), function GetColumnValue, file ../src/odbc.cpp, line 628.
```

for running those commands I would do that all on the box running db2? the db2 instance is on a VM in the cloud... I guess I could scp ibm_db over to it and then proceed. Is that the intention?

**Comment by bimalkjha** [comment]
@dhaazen you can run these commands on your mac where ibm_db is installed and you are able to repro the issue. If you can repro the issue on linux vm too then it would be great as we can collect larger trace on linux, mac has some limitation. For linux, commands would be as below:
```
export IBM_DB_HOME=<path_to_ibm_db>/installer/clidriver
export PATH=$IBM_DB_HOME/bin:$IBM_DB_HOME/adm:$IBM_DB_HOME/lib:$PATH
export LD_LIBRARY_PATH=$IBM_DB_HOME/lib:$LD_LIBRARY_PATH
db2trc on -f 1.trc
```
Now run your app to repro the issue. Immediately after repro, run below commands:
```
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
```
Thanks.

**Comment by bimalkjha** [comment]
Also, by looking on the last shared traces, we suspect your application is calling result.closeSync() or stmt.closeSync() after conn.close(). Please update app to call result.close or stmt.close before conn.close. More we can tell by looking on code snippet only. Anyway, we need db2trace files to find the root cause. Thanks.

**Comment by dhaazen** [comment]
@bimalkjha Data requested has been sent in an e-mail

**Comment by bimalkjha** [comment]
@dhaazen Requesting you to check with latest code. I pushed some defensive code. Since, we don't have any repro, so we are dependent on you. Hope it should be fine. Thank you.

**Comment by dhaazen** [comment]
@bimalkjha I retried with the latest and it did not seem to help. I sent you a test file I created which repeatedly access the DB and it consistently breaks with an "Abort trap: 6" Error. Let me know if this helps.

**Comment by bimalkjha** [comment]
@dhaazen Please try using smaller image file. Abort is due to system has no more memory to allocate. your test.js is calling the same function recursively. call the function in a loop. Abort is not the original issue. Please repro the original issue and share the error message that you see with assert. Also, please collect fresh db2trace and db2cli.ini trace as before. Thanks.

**Comment by bimalkjha** [comment]
@dhaazen please update your app as suggested in codeSnipet.js file shared via email. It should work fine. I also pushed one sample [webapp.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/webapp.js) . It is doing the same thing and working fine. Please check it. Thanks.

**Comment by bimalkjha** [comment]
@dhaazen Thanks for sharing code for your app. I updated code of your app to use pooled connection and it seems working fine. Please update your db.js file as below:

Replace:

`var ibmdb = require('ibm_db');`

To:
```
var Pool = require('ibm_db').Pool;
var ibmdb = new Pool();
```

I ran your app after this modification 5 times and it seems working fine. Please verify and confirm.

Thanks and Regards,
Bimal Jha

**Comment by bimalkjha** [comment]
@dhaazen Please let us know if we can close this issue. Thanks.

**Comment by rajocu** [comment]
We are also running into this issue. The proposed workaround (to use pooled connections) has reduced the frequency of the  crashes but has not resolved the root cause. They still occur.

**Comment by simararneja** [comment]
I faced the similar issue: Node app is crashing unexpectedly with the following error.

../src/odbc.cpp:620: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != -2' failed.

Node version: 6.11.0
IBM_DB2 version: 2.3.0

I see the issue is closed in 2.0.0 but it has popped up in one of the latest release.

**Comment by bimalkjha** [comment]
@simararneja This error comes due to wrong application logic or you are not closing the stmt or result object in the application but only close the conn object. Please check your application code and update according else, open a new issue with test program to repro the issue or part of application code to check the logical error. Thanks.

**Comment by simararneja** [comment]
@bimalkjha Thanks for the quick response. Was able to resolve it!
