### ISSUE TITLE
SQL "NO DATA FOUND" is not returned when updating a row that does not exist

### ISSUE THREAD

**Issue by gabrielmancini** [ibmdb/node-ibm_db#209]
http://www-01.ibm.com/support/docview.wss?uid=swg1JR27415
Error description
If a user tries to update a row that does not exist, there is no
java.sql.SQLException or java.sql.SQLWarning thrown to indicate
that the
row did not exist. Since the SQLCODE is only trapped through
these two
objects in Java, the application thinks that the row existed
and the update was successful.

The problem is with legacy jdbc app/net driver.
Local fix
Use ExecutionContext.getUpdateCount() to get the number of rows
updated.
Problem summary
Users Affected: Users Using Legacy JDBC .app or .net driver.

Problem Description: When using the JDBC app driver,
COM.ibm.db2 .jdbc.app.DB2Driver, or the JDBC net driver, COM.ibm
.db2.jdbc.net.DB2Driver, if an update is done to a row that does
not exist, java.sql.SQLException or java.sql.SQLWarning will not
throw and error to indicate the row does not exist.

Problem Summary: When using the JDBC app driver,
COM.ibm.db2 .jdbc.app.DB2Driver, or the JDBC net driver, COM.ib
.db2.jdbc.net.DB2Driver, if an update is done to a row that doe
not exist, java.sql.SQLException or java.sql.SQLWarning will no
throw and error to indicate the row does not exist.
Problem conclusion
Problem First Fixed in Version 9 Fixpak 5 (s080512).
Temporary fix
Use ExecutionContext.getUpdateCount() to get the number of rows
updated.

i know this is a java error but i had the same issue here in node

**Comment by bimalkjha** [comment]
@gabrielmancini This reported problem is related to JDBC driver and not ODBC driver. ibm_db is using ODBC driver. Also, fix of this problem was first delivered in db2 v9.1fp7. currently ibm_db is using db2 v10.5fp5. So, fix is already included.

Please let us know your expectation by reporting this issue here. Are you facing any issue with ibm_db?  If yes, please share test script to reproduce the issue. Else, confirm to close the issue. Thanks.
