### ISSUE TITLE
Build a pure JavaScript platform independent version of this driver

### ISSUE THREAD

**Issue by behrangsa** [ibmdb/node-ibm_db#232]
Similar to a JDBC Type 4 pure Java driver.

**Comment by bimalkjha** [comment]
Thanks @behrangsa for this request. Benefit one gets with the huge effort required to build such driver is not much at the moment. We'll keep track of how many such requests come in about it. That'll help us to make decision in future.

**Comment by rmg** [comment]
The effort on this definitely seems high.. but the benefits are _not_ small.

This would resolve open issues #235, #239, #243, #272, #274, #275.

It would also resolve closed issues that were not actually resolved, such as #263, #264, #236, #229, to name a few.

**Comment by sam-github** [comment]
It may be a lot of effort, but most DB APIs in node eventually go either pure javascript, or js with an optional binary addon, because of the difficulty of dealing with binary addons,  cf. mongo, mysql, postgres, redis, etc.. Binary addons that require external network access to build are even harder to deal with in the enterprise.

**Comment by behrangsa** [comment]
[Emscripten](http://kripken.github.io/emscripten-site/index.html) should reduce the amount of work needed for porting the C++ driver to JavaScript.

It might be possible to compile the JDBC driver to JavaScript using tools such as GWT too.

Both approaches might require extra work and tweaking though.

**Comment by Danwakeem** [comment]
I wanted to use this library in an IBM Cloud Function on Bluemix and I couldn't because according to the Bluemix documentation you can only use JavaScript dependancies.
> [The archive file upload currently does not support binary dependencies but rather only JavaScript dependencies.](https://console.bluemix.net/docs/openwhisk/openwhisk_actions.html#creating-and-invoking-javascript-actions)

It does seem silly that Bluemix Cloud Functions do not include this package as part of the list of default packages but I think they just went with whatever in included in OpenWisk by default. 

Just wanted to throw this out there since @bimalkjha said if enough people ask for this you guys may consider converting this package. I know this is no small task it would be much appreciated! 😄

**Comment by bimalkjha** [comment]
@Danwakeem Many users are already using ibm_db package on Bluemix. It works fine on Bluemix without any issue. If you are facing any issue in using this package on Bluemix, please open a new issue. Thanks.

**Comment by Danwakeem** [comment]
It does work without issue on the Bluemix Node.js runtime but I was told by IBM support since this package uses a binary file I can not run it as a IBM Cloud Function (formerly known as OpenWisk). 

I guess it is possible the support team misunderstood so I will keep in touch with support to see if they can provide any further clarity.

**Comment by Danwakeem** [comment]
For anyone else looking at my previous comments, IBM Cloud added support for this package [as a built-in package](https://console.bluemix.net/docs/openwhisk/openwhisk_reference.html#openwhisk_ref_javascript) for Node v8 Cloud Functions :) Yay!

**Comment by behrangsa** [comment]
Another option could be porting it to WebAssembly.

Also IBM can lead a NEE (Node Enterprise Edition) effort and design specifications similar to JCP specifications but for Node (e.g. NDBC: Node Database Connectivity).

**Comment by bimalkjha** [comment]
@behrangsa IBM Client drivers (ODBC, JDBC, Open Source) are used to provide connectivity to Db2 server running on Linux, Unix, Windows, z/OS and iSeries platforms. These client drivers have free connectivity for Db2 LUW server, but connectivity for "Db2 for z/OS" and "Db2 for iSeries" is not free. User requires Db2 Connect license from IBM to communicate with Db2 for z/OS: https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity

IBM ODBC and JDBC drivers are not open sourced. All IBM Open Source drivers like Node.js driver, Python driver, Ruby Driver, Perl Driver, PHP Driver and Go Driver are using ODBC driver for connectivity to enforce the requirement of Db2Connect license for z/OS and iSeries servers. If we write pure JavaScript version of this driver, we can not enforce the db2connect license requirement as any one can modify the source code and have free connectivity to z/OS server. This will be a big loss of db2connect revenue for IBM. Pure JS driver will nullify the existence of db2connect license. Hence, IBM can not build such driver. Open source community is free to take responsibility and develop such driver. 
Knowing this fact, I am closing this issue now. Thanks.

**Comment by bimalkjha** [comment]
Just to add more info, keeping ODBC driver under the cover of all IBM Open Source driver, reduces maintenance effort too about these 6 kind of OS drivers. To exploit new capabilities/features of target Db2 servers, we just enhance ODBC & JDBC drivers. Adding capability in ODBC driver to utilize new feature of new release of Db2 server, automatically makes these capabilities available for open source drivers too as OS drivers are based on top of ODBC driver. This way, we reduces codes and maintenance effort of odbc drivers. Thanks.
