### ISSUE TITLE
Informix 10.0 Connection Error

### ISSUE THREAD

**Issue by tryqwe** [ibmdb/node-ibm_db#25]
Hi,

Thanks a lot for this module. 

I'm having the following issue when trying to connect to an informix 10.0 server:

[IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001

Using the following DSN:
Database=myDataBase;Host=192.168.10.10;Server=db_engine_tcp;Service=1492;
Protocol=onsoctcp;UID=myUsername;Password=myPassword;

Does it support Informix V10.0?
In case it does, what I'm doing wrong? With jdbc / php-pdo it's working fine.

Thanks in advance,

tryqwe

**Comment by avikalar** [comment]
Hi,

You maybe running into this error because either you are connecting to wrong PORT or there is no entry for DRDA protocol nettype in sqlhost file of Informix server. To check if DRDA is enabled please check entries in your sqlhost file by running 'echo $INFORMIXSQLHOSTS'. If it is empty or not set you can find sqlhost file under $INFORMIXDIR/etc/sqlhosts. If the sqlhost file has an entry with drsoctcp protocol , then use that port number in the connection string. If not found enable DRDA by adding a new entry into the sqlhost file. Then you can connect to the db using the following connection string with the port number taken from the sqlhost file entry for drsoctcp and protocol set to TCPIP.

HOSTNAME=myserver.domain.com;PORT=****;DATABASE=sample;PROTOCOL=TCPIP;UID=UUU;PWD=PPP;

https://code.google.com/p/ibm-db/issues/detail?id=116 - This link talks about a similar issue. Please look into this for further reference. 

thanks,
Avinash

**Comment by tryqwe** [comment]
Thanks a lot for the fast reply. 

Hopefully when my client upgrades to a newer version, I'll be able to use nodejs with this plugin without a problem. :)

**Comment by avikalar** [comment]
You are welcome. I will close this issue for now. When you start using our package and if you need any help you can open a new issue.
