### ISSUE TITLE
Error SQL30081N

### ISSUE THREAD

**Issue by jeanabraham** [ibmdb/node-ibm_db#254]
Hi,

Using ibm_db@2.0.0,  I am trying to do this [basic run](https://github.com/ibmdb/node-ibm_db#quick-example)  against a DB2 instance from a NodeJS server instance. I am able to connect to the DB2 instance with the IBM Data Studio standalone client. But when I try to connect and do a query, I'm getting the below error. Any Ideas? Thanks!

```
{ [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "49.9.172.216".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001
]
  errors: [],
  error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "49.9.172.216".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001\n',
  state: '08007' }
```

**Comment by rhtpandeyIN** [comment]
Hi @jeanabraham , I think your server is refusing connection request here. Try to use other available ports for connection. or it could be firewall access issue. Thanks

**Comment by jeanabraham** [comment]
Hi @rhtpandeyIN, I am able to connect on the same port via a standalone client and see the list of tables. Its only when I try to connect via node/ibm_db. I doubled checked that the host/port is accessible from the host which I'm trying from.

**Comment by rhtpandeyIN** [comment]
Could you please check with other system (If possible), because this is clearly a communication error.
Typically SQL30081N error means a communication error in the tcp/ip layer between the client and server.
This happens when server is refusing connection (tcp/ip not enabled), or firewall not allowing connection or may be your connection string is not correct. 

Please visit this link for info about SQL30081N error: http://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.messages.sql.doc/doc/msql30081n.html

Thanks.

**Comment by jeanabraham** [comment]
Hi @rhtpandeyIN, the issue that I'm facing seems to be the exactly the same as issue https://github.com/ibmdb/node-ibm_db/issues/145

but I'm trying against DB2. Is there a equivalent config or port that I need to ask the DBA admin to check? Thanks!

Jean

**Comment by jeanabraham** [comment]
Running into this issue https://github.com/ibmdb/node-ibm_db/issues/33 when I change the PROTOCOL to HTTP or onsoctcp.

**Comment by bimalkjha** [comment]
@jeanabraham I think your standalone client is local to the server? i.e. both client and DB2 server is in the same system?
Error SQL30081N clearly tells that server is not enabled to accept connection over TCPIP. You need to run below commands on db2 server:
```
db2set DB2COMM=TCPIP
db2 update dbm cfg using svcename <tcpip_port_no>
db2 terminate
db2stop
db2start
```
Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @jeanabraham , are you still facing this issue or you got the solution ? Please do share your experience thanks.

**Comment by opepermans** [comment]
I had the same problem. Turned out I used the wrong port number. Port number of the DB in standard setup is 50000. I accidentaly used the port of the Data Server Manager (11080) and got: 
----
error:  [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "::1".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001
----
