### ISSUE TITLE
why is db2 uninstalling packages during its install?

### ISSUE THREAD

**Issue by sam-github** [ibmdb/node-ibm_db#274]
https://github.com/ibmdb/node-ibm_db/blob/master/installer/driverInstall.js#L322

^---- This appears to be preventing deployment in some situations. When packages are flattened, its not really possible to know whether you are uninstalling packages required by the application.

Why is this being done?

**Comment by rmg** [comment]
Ouch. It looks like this was done in 60d05260321557b6372744682f6d7051fe099bff to address #192.

**Comment by rhtpandeyIN** [comment]
@rmg you got that right :) script is only removing such packages which has been used for downloading and pre-installation purpose, it won't remove application required packages anyhow. Thanks.

**Comment by bnoordhuis** [comment]
I think Sam is telling you that with flat packages this is actually uninstalling the user's packages.

**Comment by rhtpandeyIN** [comment]
Well I don't think so it should happen, have you seen it happening? because it removes the packages from inside ibm_db 'node-modules/' directory, and I don't think it should affect other packages or application module.
If you have different observation please share with us. Thanks.

**Comment by bnoordhuis** [comment]
From https://docs.npmjs.com/how-npm-works/npm3:

> While npm2 installs all dependencies in a nested way, npm3 tries to mitigate the deep trees and redundancy that such nesting causes.
>
> npm3 attempts this by installing some secondary dependencies (dependencies of dependencies) in a flat way, in the same directory as the primary dependency that requires it.

IOW, npm >= 3 uses a flat node_modules structure instead of the nested one that #192 assumes.

**Comment by rhtpandeyIN** [comment]
Yes I got it, well as per the doc there are two cases,  (If nan >= 3)
1) When ibm_db uses the same dependency version as other modules are using then it will go to root directory of installation i.e: "node-modules". and in that case "uninstall command" will remove dependencies form the root directory itself. (But when I observed and checked after installation those dependencies were still there - may be because some other dependency module downloaded them again).
> Currently we are uninstalling following dependencies and when I checked back after installation all of >those were there in root directory.
>"var packages = ["nan", "fstream", "unzipper", "targz", "request"];"

2) If ibm_db using different version of dependency compared to other dependency modules, then that particular dependency will install in a nested way i.e: it will store inside "ibm_db/node-modules" directory not into the root. and in this particular case script will uninstall nested dependency only (like we supposed till now).

So do you have any suggestion for that? I mean what you think should we continue with the same approach or remove that uninstall part?

**Comment by sam-github** [comment]
I have not been able to reproduce this myself, but our customer sees it, and I'm trying to get repro info from them. Obviously its a large app full of proprietary code, but we are working to find a minimal repro.

```
4544 info build /data/web/services/svc/26/work/6b86e1190c7d5fb641d4716efdbf48065ebbbcef.1496248703684/node_modules/ibm_db/node_modules/nan
4545 verbose stack Error: ENOENT: no such file or directory, open '/data/web/services/svc/26/work/6b86e1190c7d5fb641d4716efdbf48065ebbbcef.1496248703684/node_modules/ibm_db/node_modules/nan/package.json'
4545 verbose stack     at Error (native)
4546 verbose cwd /data/web/services/svc/26/work/6b86e1190c7d5fb641d4716efdbf48065ebbbcef.1496248703684
4547 error Linux 3.10.0-327.el7.x86_64
4548 error argv "/afs/eda.fishkill.ibm.com/project/web/tools/.bin-linux/node" "/afs/eda/project/web/tools/bin/npm" "rebuild"
4549 error node v6.9.1
4550 error npm  v3.10.8
4551 error path 
```

Or at least, this looks very much like the result of the `npm uninstall`.

**Comment by sam-github** [comment]
IMO, #192 is not a valid bug. The presence of 2 or 3 dependencies used to download and build the addon has negligible overhead, its not a problem that needs solving. The solution used is non-deterministic, the result of the `npm uninstall` during the running of an install script are not defined, and unlikely to be predictable or portable. I would expect the result to vary depending on npm version, and worse, on the exact dependencies of the package tree above and around ibm_db. I don't think its even guaranteed that the version of npm doing the install is going to be the version of npm run by the install script. The solution seems like its delving into troublesome areas. I've never seen any other package that uses nan uninstall nan after the fact, and its not good to step off the beaten path with npm, you can end up in the brambles pretty quickly.


Also, @rmg remembers these details better than I, but the timing of download of dependencies and the running of package install scripts was not deterministic on earlier npm versions, so you may need to actually "bundle" any dependencies of the install script: https://docs.npmjs.com/files/package.json#bundleddependencies

**Comment by rmg** [comment]
> Also, @rmg remembers these details better than I, but the timing of download of dependencies and the running of package install scripts was not deterministic on earlier npm versions, so you may need to actually "bundle" any dependencies of the install script

That is absolutely correct. The only _reliable_ way to use dependencies in install scripts is if they are bundled. Generally it is best to avoid them entirely whenever possible.

**Comment by rmg** [comment]
It looks like **6M** of the "unwanted" dependencies is `request`. As far as I can tell, that's only so that `HTTP_PROXY` is supported automatically.

The next largest is **1.6M** for `unzipper` which is only required because the Windows binaries are in a .zip file instead of a .tgz file like the other platforms. It is also used to extract `build.zip` which is bundled in the build, but that should actually be extracted in git and stored uncompressed instead of as a zip file since it would allow better compression of both the published tarball _and_ the git repo itself.

The `nan` dependency is small and important and there's no real benefit in deleting it at all.

The `fstream` and `targz` dependencies could be replaced by the single `tar` package which is smaller than each of those, better tested, and faster.

**Comment by rmg** [comment]
If size is a concern, it might also be worth considering excluding the **2MB** `test/` folder from the published package.

**Comment by rhtpandeyIN** [comment]
I think building a pure JavaScript version would be a nice deal, but obviously it will require huge time and effort. Well we are looking into it, and for now I think rather than uninstalling packages during installation time, we can "remove -rm" the nested modules from inside "ibm-db/node-modules" directory. I think it won't create that problem, flat dependencies won't impact by doing this.

**Comment by sam-github** [comment]
Please just remove the code, its fragile and unnecessary. I've never seen a node application remove its dependencies, and doing so will break `npm rebuild`, which is still blocking deploy of `ibm_db`.

**Comment by rhtpandeyIN** [comment]
got it, I will do that changes but first need to consult with team. Thanks.
