### ISSUE TITLE
ibm_db.debug(true) is not stringifying objects

### ISSUE THREAD

**Issue by micophilip** [ibmdb/node-ibm_db#288]
When doing `require('ibm_db').debug(true);`, non-stringified objects get printed so it looks like this:
```
Pool {
options: { connectTimeout: 60 },
maxPoolSize: 0,
index: 0,
availablePool: 
 { 'ERADICATED-CONNECTION-STRING': 
    [ [Object],
      [Object],
      [Object],
      [Object] ] }
```

**Comment by sam-github** [comment]
If ibm_db is using https://nodejs.org/api/util.html#util_util_inspect_object_options, it is possible that the `depth:` is not set. It defaults to `2` and could be increased, or set to `null`

**Comment by rhtpandeyIN** [comment]
Hi @sam-github, is it application specific task or we need to do it in our module. I am not sure about this, as we are just requiring the "util" module and not using it anywhere. So as per the doc you mentioned - it is stating that by setting depth to null it will recurse indefinitely.
So my query is - Do we need to set it in our module or application can set it?

**Comment by sam-github** [comment]
You are calling it implicitly:

> exports.debug && console.log(getElapsedTime(), "odbc.js:queryResult() => ", sql);

should be changed to

> exports.debug && console.log(getElapsedTime(), "odbc.js:queryResult() => %j", sql);

if you want to log complex objects,  because `console.log()` calls `util.format()` on its arguments, and `util.format()` calls `util.inspect()` on any extra object arguments (ones that don't have a format specifier, like `sql` above in your original code) to turn them into strings. If you use `%j` as a format specifier it will print the entire object.

FYI, I highly recommend moving away from your home-rolled debug system and moving to  https://www.npmjs.com/package/debug. It allows people to turn on debug output using an env variable when they discover they need to troubleshoot, rather than having to make source code modifications.
