### ISSUE TITLE
cannot connect mvs db2 in docker

### ISSUE THREAD

**Issue by zhouzx** [ibmdb/node-ibm_db#289]
I have the license file ,and put it into folder /home/test/node_modules/ibm_db/installer/clidriver/license 
But got following error.
{ Error: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

    at Error (native)
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968\n',
  state: '42968' }

The same code can be run in my laptop successfully.

**Comment by rhtpandeyIN** [comment]
Hi @zhouzx , 
I think the license file you have copied to the license directory is from a different release.

Diagnosing the problem
--------------------------------

Go to the installation_path/bin folder and run db2level. For example it may show the following:

$ db2level
DB21085I Instance "DB2" uses "64" bits and DB2 code release "SQL09076" with
level identifier "08070107".
Informational tokens are "DB2 v9.7.0.6", "s120629", "IP23421", and Fix Pack
"6".
Product is installed at "/opt/IBM/dsdriver/V9.7_FP6/dsdriver/.".

View the contents of the license file in a text editor. For example, the file db2consv_zs.lic may show contents such as the following.

License Certificate for 5724-B62 IBM DB2 Connect Unlimited Edition for zSeries, V9.5

In this example, the IBM Data Server Driver installed is from v9.7 but the license file is from v9.5. The license files are not compatible with other releases.

Resolving the problem
-----------------------------------

Obtain the DB2 Connect license for the release that matches the db2level and copy it into the installation_path/license directory where the IBM Data Server Driver package is installed.

In order to obtain a DB2 Connect license, please visit the following link:
`http://www-01.ibm.com/support/docview.wss?uid=swg21305417`

**Comment by kentonbmax** [comment]
I am currently getting this error. The readme make not mention of needing a license file for linux or where it should reside. Can someone please help?

**Comment by bimalkjha** [comment]
@kentonbmax License file is required only if your database is on z/OS or AS400 system. If your database is on Linux server then no license file is required for ibm_db.
