### ISSUE TITLE
Slow Query Response

### ISSUE THREAD

**Issue by hectotruj** [ibmdb/node-ibm_db#364]
## Issue
Query response takes too long

## Situation
A query I ran on the DB2 dashboard, and then again on DBeaver, returns in less than 2 seconds. However, it takes about 17 seconds in Node using this library. 

## Data
The data being returned contains about 50k rows

**Comment by rhtpandeyIN** [comment]
Hi @hectotruj , Can you please share some repro test case for the issue, what exact query you are trying to run? is it same for every query or for some queries?

If you are comfortable to provide time difference log/data/output, please provide it as well.

Thanks.

**Comment by hectotruj** [comment]
Hi @rhtpandeyIN , thanks for reaching out. I can't provide a lot of the code, but I can share the logic behind it.

```
SELECT * FROM table1 t

**Comment by rhtpandeyIN** [comment]
Thanks for providing the information, but to make sure this is because of node-ibm_db particular version, we need more data/information. 

Would you be able to help us, if I request you to check the same query with different node versions, and with different node-ibm_db versions? 
At least few cases:
1) latest node-ibm_db with node 8.X, node 7.X and node 4.X
2) node-ibm_db version which you are using (if not latest), with node 8.X, 7.X, 4.X
3) node 8.X, 7.X, 4.X with node-ibm_db previous releases.

Above information will be required to analyse/determine the exact issue, and thanks in advance for your help.

**Comment by Louis-7** [comment]
I'm using node 4.x with ibm_db2 0.0.19, having same issue. So I'm trying to upgrade ibm_db2 but I met several errors when execute query.

**Comment by Louis-7** [comment]
I tried to upgrade ibm_db to 1.0.0/2.0.0/2.2.0, all these version have slow response. Much slower than execute SQL in Data Studio (GUI).

**Comment by hectotruj** [comment]
Hi @rhtpandeyIN , I apologize, but we haven't had the time to test it and I'm not sure we will anytime soon. But it seems @Louis-7 is also having the same issue. And is a problem that has come up before 
[Node 6.x/8.x slower timings with ibm_db than Node 4.8.3 #269](https://github.com/ibmdb/node-ibm_db/issues/269)

**Comment by rhtpandeyIN** [comment]
As per the discussion with Ziyad closing the issue. (Issue not exist anymore).
Please feel free to reopen or comment below in case of further queries.
