### ISSUE TITLE
CLI0123E: SQL data type out of range. SQLSTATE=HY004 on ibm bluemix (version  	DB2LUW 10.5.4)

### ISSUE THREAD

**Issue by kazan417** [ibmdb/node-ibm_db#39]
getting this errr when trying to use

**Comment by kazan417** [comment]
ssory? this is not driver issue? but sails-db2 adapter issue that i use

**Comment by kazan417** [comment]
again thiking? that is driver issur? because of i tested thi driver dirrectly using demo test app
https://github.com/data-henrik/db2visitors.git but it crashed with same error 
[Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
Connection Closed

**Comment by bimalkjha** [comment]
Are you able to run your application locally? Please share the output of quick example shown here: https://github.com/ibmdb/node-ibm_db. Also, run it first locally.

**Comment by kazan417** [comment]
i am running application locally, but database on remote host.
now i am trying to run  quick example ang i get 
 { [Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "JHSNKSZT.USER" is an undefined name.  SQLSTATE=42704
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "JHSNKSZT.USER" is an undefined name.  SQLSTATE=42704\n',
  state: '42S02' }
done
i have low register username on remote server and in sended string, but driver sende big register username.

**Comment by bimalkjha** [comment]
@kazan417 seems you are able to connect to the server now as this error is coming from database server after connection. In the quick example just change query to "select 1 from sysibm.sysdummy1" and you'll get the 1 as result. I have updated the quick example too with the same query now. thanks.

**Comment by kazan417** [comment]
connection to server is work now, 
but i am still getting CLI0123E: SQL data type out of range. SQLSTATE=HY004 when i trying to run thes simple app https://github.com/data-henrik/db2visitors. whats wrong???

**Comment by bimalkjha** [comment]
@kazan417 I am able to repro the issue now. It seems some data binding issue. But seems it is working for data-henrik now. Please check this [post by data-henrik](https://github.com/data-henrik/db2visitors/issues/1#issuecomment-120431174). I am pasting the same as below:
`I don't have time right now to look into it due to travel. However, changing the parameters of the execute() statement in db2access.js succeeded in inserting a record again. Not sure what has changed, but could be that "massaging" the values of the IP record is needed before passing them as parameters to execute().`

**Comment by kazan417** [comment]
fortunaly my framework support excellent abstraction layer and now i use other database - mysql with sails-mysql adapter, because of sails-db2 does not work.
