### ISSUE TITLE
 [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 8" could not be loaded.  SQLSTATE=42724    at Error (native)

### ISSUE THREAD

**Issue by roy27787** [ibmdb/node-ibm_db#407]
Getting the following error message when setting Security=SSL at the end of the connection string.
I tried setting $PATH, $LIB and $LD_LIBRARY_PATH to point the following directories using absolute paths
installer/clidriver/bin
installer/clidriver/lib/icc
installer/clidriver/lib

Using Mac OSX (Sierra),  ibm_db 2.3.1  and NodeJS v6.9.1

Thanks

**Comment by bimalkjha** [comment]
@roy27787 Please share your test program to repro the issue with connection string so that we can see your connection string is proper or not.
You can try below commands too:
```
cd ibm_db/installer
. ./setenv.sh
node <your-test-file>
```
LD_LIBRARY_PATH env var do not work in Mac OSX. You need to set DYLD_LIBRARY_PATH. Also, make sure the new path is at start of these env vars. Error tell, some old version of gskit is in system and that is getting picked up by ibm_db.
Thanks.
