### ISSUE TITLE
Protocol specific error code(s): "420", "*", "*". SQLSTATE=08001

### ISSUE THREAD

**Issue by chakri14** [ibmdb/node-ibm_db#426]
After ssl configuration at Server & client side,getting below error while connecting database

SQL30081N  A communication error has been detected. Communication protocol
being used: "SSL".  Communication API being used: "SOCKETS".  Location where
the error was detected: "".  Communication function detecting the error:
"sqlccSSLSocketSetup".  Protocol specific error code(s): "420", "*", "*".
SQLSTATE=08001

Please help me to fix this.

Thanks

**Comment by bimalkjha** [comment]
@chakri14 How you configured SSL at client side?
For ibm_db we just need server certificate with extension .arm from DB2 server and use it in in the connection string as documented [here](https://github.com/ibmdb/node-ibm_db#-1-openconnectionstring-options-callback). Just search for SSL and you will get to the right point.
Please share the connection string that you are using in the application for connection. The `420` [error code](https://www.ibm.com/support/knowledgecenter/en/SSEQVQ_8.1.5/msgs.tsm/r_pdg_retcodes.html) means: 
```
420 | GSK_ERROR_SOCKET_CLOSED | The partner closed the socket before the protocol completed.
```  
It tells that server has closed the connection and it might be due to incorrect connection string or incorrect certificate file. Make sure you are using SSL port in connection string and `Security=SSL` is used in the connection string along with `SSLServerCertificate=<certificate.arm>` keyword. Thanks.
