### ISSUE TITLE
error handling in promise

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#457]
latest release 2.4.1

problem when having an error in a promise

```
conn
                    .query('select something that returns an sql error')
                    .then((data: any) => {
                       /* the data contains the error */
                   })
                  .catch((err: Error) {
                  }

```

the issue i'm facing with this version 2.4.1 is that the 'data' in the 'then' contains the Error and the catch is never reached 

thanks

**Comment by bimalkjha** [comment]
@huineng I think it is due to this commit: https://github.com/ibmdb/node-ibm_db/commit/c0b560aa7e3c9d5d4dfdc0eb4bbf04caa7adfd68 

It seems as the result of correction at line 548 in odbc.js file for deffered.resolve(). We have updated the file `test/test-querySync-select-with-exception.js` too accordingly. Please check it and let us know if you still feel the new behaviour is incorrect. Thanks.

**Comment by huineng** [comment]
Looks ok 
thanks
