### ISSUE TITLE
Empty result set returned if stale connections are used in subsequent calls

### ISSUE THREAD

**Issue by PavaniKa** [ibmdb/node-ibm_db#483]
With the latest ibm_db we are able to reproduce the stale connections issue.

App Environment: **IBM Bluemix**
Database: **DashDB MPP** on IBM Cloud
NodeJS version: **V8.11.4**
ibm_db version: **V2.4.1**
_**Connection Pooling is enabled in NodeJS environment**_

Steps followed to reproduce this issue:
1. NodeJS app is restarted to make sure all earlier connections in the pool are recycled.

2. We ran a report from UI. UI called NodeJS API, API ran a query on DashDB. At this point one connection is created in the pool. Let's call this CONN1. This connection successfully got the resultset/cursor back from database.

3. We ran the same report in UI again by changing a few parameters. While the connection from API to database is still open, to simulate the database connection interruption/termination issue, we killed the query from IBM Data Studio. Below error is logged in callback.

`Error: [IBM][CLI Driver] SQL1224N  The database manager is not able to accept new requests, has terminated all requests in progress, or has terminated the specified request because of an error or a forced interrupt.  SQLSTATE=55032`

- 3.a Below query is used to monitor active database queries from IBM Data Studio

`select * from SYSIBMADM.MON_CURRENT_SQL;`

 - 3.b Below query is used to kill the any currently running queries from IBM Data Studio

`CALL SYSPROC.ADMIN_CMD( 'force application (XXXX)' );`

4. We ran the same report again from UI. A few report filter parameters are changed to ensure a fresh report is running. UI called NodeJS API, API ran the query on DashDB. At this point there is one connection in the pool CONN1, and it is used to run the query.

5. There are no active queries running in DashDB when we run the monitor query (mentioned 3.a) 

6. On NodeJS API, the stale connection CONN1 returned an empty cursor/resultset [] in the callback. 

7. Repeated steps 4, 5 multiple times with same results.

With this behavior we can not rely on using the connection pooling. We expect  one of the below behaviors with this connection CONN1.
1. This connection can now communicate to database again.
2. This connection will be destroyed from the pool as it is no longer can communicate with database.

**Comment by bimalkjha** [comment]
@PavaniKa Thanks for explaining the issue in detail. Trying to reproduce it as you described. If you can share any small test file to repro the behavior, it will help. thanks.

**Comment by bimalkjha** [comment]
@PavaniKa Thanks for detailed explanation. Please see update as below:
1. When server drops the connection from client, client can know this only when it try to access the server. server do not notify the client that connection is dropped or broaken due to some network issue. If you want CONN1 should reconnect automatically internally in case of broken connection, you need to enable Automatic Client Reroute (ACR) at client side using db2dsdriver.cfg file. There is no other way to tell ibm_db to reconnect and communicate to database again. Credentials in db2dsdriver.cfg file is optional and can be used in connection string along with dsn.
2. When this connection is used first time after get broken communication, then it gets removed from pool. Until application use a connection to run query, client can not know that its a broken connection. Based on -33081 or -1224 error only client can know the connection is broken.
Thanks.

**Comment by bimalkjha** [comment]
@PavaniKa Ibm_db has an option to automatically clean the idle connections from pool after 30min of idle time. You can set it using `new Pool({autoCleanIdle: true});`.
Also, if you want to clean at different time, you can set it using `idleTimeout` pool option like: `new Pool({idleTimeout: 10*1000; autoCleanIdle: true});`. idleTimeout takes value in millisecond. Thanks.

**Comment by rophy** [comment]
@bimaljha I don't see this `autoCleanIdle` and `idleTimeout` being documented in [API Doc](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md). Which version supports this feature?

**Comment by bimalkjha** [comment]
@rophy These keywords are supported since day one but missing documentation.  Yes, cleanup is only performed when client calls conn.close() to move the connection back to available pool. conn.close() will call the cleanUp() function to clean idle connections. 
These options could help to reduce the idle connections from pool, but can not avoid -30081 error completely. ACR implementation in db2dsdriver.cfg file would avoid the -30081 error. Thanks.

**Comment by rophy** [comment]
@bimaljha  I managed to load db2dsdriver.cfg, but the problem in this issue still persists.

1. Prepare `node_modules/ibm_db/installer/clidriver/db2dsdriver.cfg` as below:

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<configuration>
   <dsncollection>
      <dsn alias="chcDB" host="dashdb-enterprise-yp-dal13-100.services.dal.bluemix.net" name="BLUDB" port="50001">
      </dsn>
   </dsncollection>
   <databases>
      <database host="dashdb-enterprise-yp-dal13-100.services.dal.bluemix.net" name="BLUDB" port="50001">
         <parameter name="KeepAliveTimeout" value="20"/>
         <parameter name="ConnectionTimeout" value="10"/>
         <parameter name="MemberConnectTimeout" value="1"/>
         <acr>
          <parameter name="enableACR" value="true"/>
          <parameter name="enableSeamlessACR" value="true"/>
          <parameter name="acrRetryInterval" value="2"/>
          <parameter name="maxAcrRetries" value="30"/>
          <parameter name="affinityFailbackInterval" value="2"/>
          <alternateserverlist>
            <server hostname="dashdb-enterprise-yp-dal13-100.services.dal.bluemix.net" name="S1" port="50001"/>
            <server hostname="dashdb-enterprise-yp-dal13-100.services.dal.bluemix.net" name="S2" port="50001"/>
          </alternateserverlist>
          <affinitylist>
            <list name="list1" serverorder="S1,S2"/>
          </affinitylist>
         </acr>
      </database>
  </databases>
</configuration>
```

2. Run `node_modules\ibm_db\installer\clidriver\bin\db2cli validate`, says:

```
Success: The schema validation completed successfully without any errors.
```

3. Run my nodejs code with connection string as: 

```
DSN=chcDB;UID=my_username;PWD=my_password;Security=SSL
```

4. Do a query -> OK

5. In DB2 UI, force drop the connection which was created by the ibm_db pool.

6. Do a query -> SQL30081N 

7. Do a query -> empty result set, no error.

What am I doing wrong?

**Comment by bimalkjha** [comment]
@rophy This issue seems same as #497 . Please see the update their. You need to add <clientaffinitydefined> section under <acr> section in your db2dsdriver.cfg file as below:
```
                <clientaffinitydefined>
                    <client name="client1" hostname="localhost" listname="list1"/>
                </clientaffinitydefined>
            </acr>
```
After that it should work. The db2dsdriver.cfg file contents and instructions that I shared in issue 497 is working fine for me. Thanks.
