### ISSUE TITLE
Connecting to Informix

### ISSUE THREAD

**Issue by jozsefd** [ibmdb/node-ibm_db#506]
Although, the project description includes IBM Informix, it seems that connecting to an Informix database is not supported by 'ibm_db' at all. I have tried all possible combinations of Connection Strings and even DSN names which worked flawlessly with isql on my system.
Can you please add an example for connecting to Informix? 
Or just remove Informix from the description?

**Comment by bimalkjha** [comment]
@joransiu Connecting to Informix using `ibm_db` is same as DB2 servers. Only difference is in the connection string, you need to use `drsoctcp` port of IDS not the `onsoctcp`. ibm_db connects to Informix using DRDA. If your server is configured properly to communicate using `drsoctcp`, ibm_db connects too!
Please check [this doc](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.admin.doc/ids_admin_0207.htm) to know how to configure Informix Server to communicate using `ibm_db`. Thanks.

**Comment by jozsefd** [comment]
@bimalkjha thank you very much for your answer! I set up the drsoctcp in sqlhosts, now I am getting the following error on connect:
```
Error: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004
state: 'HY000'
sqlcode: -1042 
```
Not quite sure if I need to add some IDS specifics to the connect string:
`"DATABASE=stores_demo;HOSTNAME=ol_informix1210;UID=informix;PWD=****;PORT=9702;PROTOCOL=TCPIP"`
There is a DRIVER tag, but didn't find any example for IDS.

**Comment by bimalkjha** [comment]
@jozsefd This error is due to a bug of Informix Server. To suppress SQL1042C error, you need to use Authentication=SERVER in connection string. Please share the OS name of client system where you have installed ibm_db.

This issue is already reported by issue #227 . Please refer it for detail and solution. To fix it, you can cd to `ibm_db/installer` directory and execute `ifx.sh` script for non windows platform. If you have executed ifx.sh, then no need to add `Authentication=SERVER` in connection string. After that, you can test the connectivity by updating connection string in `ibm_db/installer/testODBCConnection.sh` script. Thanks.

**Comment by jozsefd** [comment]
@bimalkjha thank for your support, Authentication=SERVER in the connection string was the solution!
I test ibm_db on Ubuntu 18.04 with node v10
