### ISSUE TITLE
[ERROR] [Ldap Config] - { Error: [IBM][CLI Driver] SQL30081N

### ISSUE THREAD

**Issue by juanitodur** [ibmdb/node-ibm_db#511]
Hello,

I have a node js app which I am not able to initiate. After npm start, the app loads, I get the url and get to log in screen. I was previosly granted access to app db. Nevertheless, when I click sign in I am redirected to ibm.com hompage, not the app homepage. 

I get the following error on the console.

[2019-02-26T09:47:58.935] [ERROR] [Ldap Config] - { Error: [IBM][CLI Driver] SQL30081N  Se ha detectado un error en las comunicaciones. Protocolo de comunicaciones que se está utilizando: "SSL".  API de comunicaciones que se está utilizando: "SOCKETS".  Ubicación donde se ha encontrado el error: "".  Función de comunicación que ha detectado el error: "sqlcctcpconnr".  Código(s) de error específico(s) del protocolo: "202", "*", "*".  SQLSTATE=08001

  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  Se ha detectado un error en las comunicaciones. Protocolo de comunicaciones que se está utilizando: "SSL".  API de comunicaciones que se está utilizando: "SOCKETS".  Ubicación donde se ha encontrado el error: "".  Función de comunicación que ha detectado el error: "sqlcctcpconnr".  Código(s) de error específico(s) del protocolo: "202", "*", "*".  SQLSTATE=08001\r\n',
  state: '08001',
  sqlcode: -30081 }
[2019-02-26T09:47:58.946] [WARN] log - [Tue, 26 Feb 2019 12:47:58 GMT[clf]] - false - "GET /auth/sso/callback?scope=openid&code=9LS7suN3ZNg7Puo21wVOvijx2Dn5pm" 302 80 1428 ms'

I have a DB2 driver created in my machine. Is it possible it is conflicting with the app? Any suggestions on what should be done?

Thanks

**Comment by bimalkjha** [comment]
@juanitodur The existing db2 driver in the system may be used here as installation updates the system environment variables. You can overwrite is using `source .../ibm_db/installer/setenv.sh` and then launch the app from this command prompt. You can set the system env vars as used in this file.
Redirection in ibm.com home page may be due to some cache in your system/app/browser. ibm_db do not do anything here.
For SQL30081N error, you may try the solutions documented [here](https://community.tableau.com/thread/104912). Also, you can update connection string for `db2cli validate` command in `ibm_db/installer/testODBCConnection.sh` file and run it to verify the connectivity.
Also, good to share your platform and node version. Thanks.

**Comment by juanitodur** [comment]
Hi, thanks for the reply. I am trying to execute the db2cli but I can't. It is not a valid command. Tried within ibm_db/isntaller/clidriver or even at  "program files"/sqllib/bin... Also it is not clear to me what should be done with the serenv.sh file. If you could please guide me a little bit, or detail... BTW, I am using DB2 driver v9.7, I was suggested also to upgrade to last version, not sure if it is impacting or not.

**Comment by bimalkjha** [comment]
@juanitodur Db2 driver v9.7 is out of support and very old. It would not work with ibm_db.
Seems your system environment variables are set to use the pre-installed db2 v9.7 driver and hence causing issue for ibm_db.
If you can uninstall the installed db2 drivers from your system and just install only ibm_db using `npm install ibm_db`, that should work. Please share your Operating System name.
Otherwise, update your system environments to use ibm_db/isntaller/clidriver/bin and ibm_db/isntaller/clidriver/lib and then issue `npm install` under ibm_db. Thanks.
