### ISSUE TITLE
Hi @brayansuarezm , one part of your problem is known issue, but to figure out the other part I need your help to understand the root cause.

### ISSUE THREAD

**Issue by lx171717** [ibmdb/node-ibm_db#525]
Hi @brayansuarezm , one part of your problem is known issue, but to figure out the other part I need your help to understand the root cause.
Can you please test the below steps, and share the output with us?

1) Please download linux clidriver tar file from below URL:
`https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz`
2) Untar it and set the untared "clidriver" directory path to "IBM_DB_HOME" environment variable.
for ex: "set IBM_DB_HOME=/c/home/clidriver"
note: cross check once that "IBM_DB_HOME" is set correctly. - echo %IBM_DB_HOME% (if windows)
3) Now try to install node-ibm_db using `npm install ibm_db` command.
4) and share the output with us.

Thanks.

_Originally posted by @rhtpandeyIN in https://github.com/ibmdb/node-ibm_db/issues/366#issuecomment-369640261_

**Comment by lx171717** [comment]
How can I  do below in the IBM cloud Cloud Foundry Nodejs,  it is Paas.

 Untar it and set the untared "clidriver" directory path to "IBM_DB_HOME" environment variable.
for ex: "set IBM_DB_HOME=/c/home/clidriver"

**Comment by bimalkjha** [comment]
@lx171717 No need to set IBM_DB_HOME on CF. That post was for local installation on Windows. If you userid & password for CF system where the code is getting pushed, then you can login via telnet/ssh and execute commands. 
I think your main issue is 526 which is due to windows version of headers files and clidriver is getting pushed on CF. Please follow the solution shared on issue 526 and you may close it. Thanks.

**Comment by lx171717** [comment]
https://github.com/ibmdb/node-ibm_db/issues/526
yes , thanks very much , the same 526.

**Comment by lx171717** [comment]
https://github.com/ibmdb/node-ibm_db/issues/526
yes , thanks very much , the same 526.
