### ISSUE TITLE
Supported DB2 versions

### ISSUE THREAD

**Issue by barriteau** [ibmdb/node-ibm_db#601]
Hi, is there a way to know if certain DB2 version are not reachable for node-ibm_db 2.6.3?

Reason why I ask is, I've been able to connect and query a locally installed DB2 11.5 instance (Windows10, node 13.5, node-ibm_db 2.6.3) but can't connect when trying from the same box to a DB2 9.5 running in a AS400.

I'm pretty sure parameters, credentials and connectivity are correct because a java based IDE (jdbc drivers) in the same machine is already connected to this 9.5 DB2 in AS400.

I just want to be sure it isn't a version/platform related issue to keep trying, could it be?

Regards

**Comment by bimalkjha** [comment]
@barriteau The difference is not due to Db2 versions but due to platform on which you have installed Db2. In working case, it is Windows,  but failure case, it is AS400. ibm_db do not has any restriction for Db2 version and platform. It works with all version and platform as supported by "IBM Data Server Driver Package" and documented in Db2 Knowledge Center.

Coming on your issue, I think you are hitting licensing error. If yes, please read [this](https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity) info. If it's not a license issue, please update database connection information in `ibm_db/installer/testODBCConnection.bat` file and execute it. If it worked, ibm_db too will work. If it fails, please share the generated files with me for investigation. Thanks.

**Comment by barriteau** [comment]
Hey Bimal, thanks a lot for your kind response, I've been checking and it seems it's a license issue indeed. As I stated before, I've been able to connect to this db from my IDE using the DB2 JDBC driver (JTOpen), so licencing for connecting in this way seem to be okay, I'll try using some of the JDBC wrappers for nodejs around, if you have any recommendation in this regard, I'm all ears ;)

Again, thanks a lot.

**Comment by bimalkjha** [comment]
@barriteau FYI, the db2connect license file for JDBC application and ODBC application are different. node-ibm_db uses ODBC license file which comes as db2con*.lic and you need to copy it under ibm_db/installer/clidriver/license directory. You need to start you application after copying the license file to be effective. Thanks.
