### ISSUE TITLE
Electron App On Windows 10 - Uncaught Error: The Specified module cannot be found. odbc_bindings.node

### ISSUE THREAD

**Issue by mitchdennett** [ibmdb/node-ibm_db#607]
This app works fine on MacOS. But when building for windows I get the following error.

```
Uncaught Error: The specified module could not be found.
\\?\C:\Users\mdennett\AppData\Local\Programs\GMC\resources\app.asar.unpacked\node_modules\ibm_db\build\Release\odbc_bindings.node
```

The file does exist in that specified location though

**Comment by bimalkjha** [comment]
@mitchdennett It should work on Windows too. Please cd to ibm_db on windows command prompt and execute `npm install > a.txt` command. Then try to run the app. If still fails, please share the generated file a.txt for investigation. Thanks.

**Comment by bimalkjha** [comment]
Please share electron version and node.js version in use too. Thanks.

**Comment by mitchdennett** [comment]
So it works if I run that app locally. But as soon as I package it up and build it it doesn't work. 

The odbc_bindings.node does get packaged with the app and it is in the correct location but when it gets referenced it says it doesn't exist.

Electron version is 7.1.2 and node version is 12.13.1

**Comment by mitchdennett** [comment]
[a.txt](https://github.com/ibmdb/node-ibm_db/files/4154489/a.txt)

**Comment by mitchdennett** [comment]
See the attached a.txt

**Comment by bimalkjha** [comment]
@mitchdennett I checked a.txt. There is no installation issue and it get installed successfully. So, it seems some environment issue.
The error message that `\\?\C:\Users\mdennett\AppData\Local\Programs\GMC\resources\app.asar.unpacked\node_modules\ibm_db\build\Release\odbc_bindings.node` does not exist by app means application is unable to load this binary. It happens if `odbc_bindings.node` is unable to find its dependent libraries while loading.

If possible, you can download dependency walker tool from http://www.dependencywalker.com/ and load `odbc_bindings.node` in dependency walker to find which dependent library is missing.

Normally, `odbc_bindings.node` has dependency on `ibm_db\installer\clidriver\bin\db2app64.dll`. You can add full path of `ibm_db\installer\clidriver\bin` directory in `LIB` system environment variable to fix the issue.

I would also like to share that ibm_db compiled in electron environment may not work in non-electron environment. Thanks.

**Comment by mitchdennett** [comment]
@bimalkjha So, I've figured it out. The problem is that when I package up my Electron app. It packs everything inside `app.asar`. Native modules are unpacked however. So inside odbc.js you are explicitly setting the LIB and PATH variables. Those however are pointing inside the asar archive. Since the native modules are unpacked they are not there. I forked the repo and made this change and it works for me on Windows now. [https://github.com/mitchdennett/node-ibm_db/blob/master/lib/odbc.js#L21-L29](https://github.com/mitchdennett/node-ibm_db/blob/master/lib/odbc.js#L21-L29)

**Comment by bimalkjha** [comment]
@mitchdennett Good to know that you got the solution. Just pasting here the updated code of `ibm_db\lib\odbc.js` L21-L29 below which fixed your issue:
```
if(os.platform() == 'win32')
{
  process.env.PATH = process.env.PATH + ';' +
                     path.resolve(__dirname, '../../../../app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin') + ';' +
                     path.resolve(__dirname, '../../../../app.asar.unpacked/node_modules/ibm_db/installer/clidriver/lib');
  process.env.LIB = process.env.LIB + ';' +
                     path.resolve(__dirname, '../../../../app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin') + ';' +
                     path.resolve(__dirname, '../../../../app.asar.unpacked/node_modules/ibm_db/installer/clidriver/lib');
}
```
Thanks and Regards,
Bimal Jha
