### ISSUE TITLE
Error: "The remote host was not found" ibm_db in node js

### ISSUE THREAD

**Issue by betogm08** [ibmdb/node-ibm_db#639]
Hello! I hope you're fine. I have an issue with my connection string in my app made with node js using express. When I make the connection in localhost, it does the connection with ease, but when I deploy my application in a dev environment using ibm cloud foundry and try to make the connection, it sends me this error:
**error: "[node-ibm_db] SQL_ERROR", sqlcode: -1336, message: "[IBM][CLI Driver] SQL1336N The remote host "hdp-master-7.datalake-hdp.zc2.ibm.com" was not found. SQLSTATE=08001\n", state: "08001"**
It is not make sense for me because in local works fine. Is there a dependency that a have to configure or something related? Could you please help me?

This is my connection string:
__DATABASE=bigsql;PORT=52000;PROTOCOL=TCPIP;UID=MyUser;PWD=MyPassword;Security=SSL;SSLServerCertificate=certificate.arm;HOSTNAME=hdp-master-7.datalake-hdp.zc2.ibm.com;__

**Comment by bimalkjha** [comment]
@betogm08 The error clearly says, the dev environment in cloud is unable to reach hdp-master-7.datalake-hdp.zc2.ibm.com. It might be some firewall related issue. I would suggest to login on the cloud system where application is deployed and try to ping hdp-master-7.datalake-hdp.zc2.ibm.com. Also, instead of using hdp-master-7.datalake-hdp.zc2.ibm.com in hostname, use IP Address of hdp-master-7.datalake-hdp.zc2.ibm.com and verify. Thanks.
