### ISSUE TITLE
Error Connecting to DB2 Container

### ISSUE THREAD

**Issue by ShahMV** [ibmdb/node-ibm_db#641]
I've setup a db2 container.  When trying to connect to the database in the container, I get the following error:

[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "::1".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "99", "*", "*".  SQLSTATE=08001

I've looked at previous issues posted here for this error which suggest an issue with the db2 server setup.  However, I don't think that's case here.  I am able connect to the database using a python test program.  I am also able to connect using the DbVisualizer tool

**Comment by bimalkjha** [comment]
@ShahMV Have you exported db2 ports from the container to be available for outside applications? If you are able to connect using python program, could you install `pip install ibm_db` in the same system where you installed `npm install ibm_db` and verify the connectivity using python ibm_db?
The error says, ibm_db is unable to get response from server and hence connection timeout is happening. It may be either due to wrong port used in the connection string or some firewall is blocking communication between ibm_db client and db2 server. Yes, SQL30081N error is purely configuration related issue. Thanks.

**Comment by ShahMV** [comment]
I've tried the python sample program and the DbVisualizer tool from the same system as where my node.js app is running.  But the python test ppm and DbVisualizer are able to connect to the database.  It is only the node.js app that is getting the error.

**Comment by bimalkjha** [comment]
@ShahMV Please share your Operating System name, node.js version and npm version.
Also, would request you to update connection string in `ibm_db\installer\testODBCConnection.sh[bat]` file for `db2cli validate` command and execute it. Please share the result of this script and generated trace files if it fails. If this script prints `SUCCESS`  then update database connection string in `ibm_db\test\config.testConnectionStrings.json` file and save it. After updating the connection string in json file, execute `node test\test-basic-test.js` and share the complete output of this test file. Thanks.
