### ISSUE TITLE
How does versioning of ibm_db work in relation to the ODBC driver versions?

### ISSUE THREAD

**Issue by wcaneira** [ibmdb/node-ibm_db#664]
Hello again, 

Once again, thank you for maintaining this package.

My question (not an issue, just a curiosity) is how do you version `ibm_db` in relation to the releases/versions of the IBM ODBC drivers?  

1. When IBM releases a new version of their ODBC drivers, do you (as maintainers) publish a new  version of `ibm_db`?

1. I notice that IBM does not put the version number of the drivers anywhere in the URI path (https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/) or each zip/tar file name.  It would seem to me that the drivers on the IBM website could change without any consumers knowing.  Is this accurate?

1. Do we know how often IBM versions the ODBC drivers?

1. Is the only way to "pin" a version of the ODBC drivers, or have a guarantee of repeatable application builds and deployments with the same ODBC driver version, to use the IBM_DB_INSTALLER_URL env var, pointed to a local copy of the drivers?  If we do that, what is the risk of a future incompatibility with new versions of `ibm_db`?  In that case, would you recommend also pinning the `ibm_db` version in our `package.json` file until an application owner is ready to consciously upgrade BOTH the npm package AND the ODBC drivers?

Thank you for your time and help

**Comment by bimalkjha** [comment]
@wcaneira Please find answer of your questions as below:
1. Version of ODBC driver and version of ibm_db has no relation. We can update version of ODBC Driver once IBM release and new installation of ibm_db of the same released version can use the new ODBC driver. No need to release a new version of ibm_db for new ODBC driver to be effective. But, we do release a new version of ibm_db if there is a major version change of odbc driver.
2. We always keep only one version of odbc driver on URI path which is the latest one. Yes, odbc driver on URI path could change without any consumers knowledge as it get used by ibm_db internally. We do this for minor version upgrade of odbc driver. For major version change, we release a new version of ibm_db because db2connect license need to be upgraded for major version change of odbc driver.
3. There is no fixed schedule. Normally major version changes every 2-3 years.
4. You can choose your own odbc driver installation. ibm_db works with all versions of IBM ODBC/CLI driver. You just need to set IBM_DB_HOME to a preinstalled odbc driver. Then ibm_db will not download the odbc driver from URI but use the one pointed by IBM_DB_HOME environment variable. Please read more about it [here](https://github.com/ibmdb/node-ibm_db#important-environment-variables-and-download-essentials). You can use the IBM_DB_INSTALLER_URL too as documented.
Thanks.
