### ISSUE TITLE
Rebuild Native Modules fails

### ISSUE THREAD

**Issue by pablord14** [ibmdb/node-ibm_db#666]
I'm getting this error on vscode when execute Rebuild Native Modules:
`Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /lib/x86_64-linux-gnu/libnode.so.64)`

Thanks.

**Comment by bimalkjha** [comment]
@pablord14 It fails due to some missing package of Operating System. I do not see `/lib/x86_64-linux-gnu/libnode.so.64` is part of ibm_db package. Solution for same issue is discussed [here](https://forum.juce.com/t/glibc-2-29-not-found-on-ubuntu-18-04/34960) for Ubuntu, probably that could help you. Thanks.
