### ISSUE TITLE
Database manager fails to load DLL

### ISSUE THREAD

**Issue by siddhant777** [ibmdb/node-ibm_db#670]
I am getting the error: 
[IBM][CLI Driver] SQL1109N The command was not processed because the database manager failed to load the following DLL: "gsk8ssl_64.dll". SQLSTATE=42724

I have created a DSN in windows machine for DB2 database and I am using IBM DB2 ODBC driver.
The Security is set to SSL and I am using arm certificate in connection string.

When I test the connection, I am getting above error:

I have already added **C:\Program Files\IBM\clidriver\bin\icc64** path into my system variable PATH and LIB.

Please suggest a way to crack this

**Comment by bimalkjha** [comment]
@siddhant777 If you are able to reproduce the problem using a small node.js test program, please edit the file `...ibm_db\installer\testODBCConnect.bat`, replace the `db2cli validate` command at line number 16 with `node <absolute_path_of_your_test_file>` and execute the `testODBCConnect.bat` script from `Administrator command prompt`. It will generate many 1.* files. Copy the output of `testODBCConnect.bat` script, zip it along with all generated 1.* files and email to bjha@rocketsoftware.com. We need to check the trace logs to know root cause of the problem. Thanks.

**Comment by bimalkjha** [comment]
@siddhant777 Please let me know if  you are still facing this issue else we can close this issue. Thanks.

**Comment by siddhant777** [comment]
The issue is related to IBM db2 driver and its configuration. Closing it here.
