### ISSUE TITLE
Getting empty result after DB server is restarted

### ISSUE THREAD

**Issue by Akash-H** [ibmdb/node-ibm_db#676]
Hi,
we are using ibm_db in our nodejs project. 
Initially we were able to get result from the queries then suddenly our DB was down. when DB was up again and we tried firing SQL queries, we were getting empty result for same query and same data in database, also didn't get any specific error related to query or connection. After DB went up, we are getting empty result set whenever we fire query.

Also we are doing connection pooling and below is the code for same 
```
import { Pool } from 'ibm_db';
pool = new Pool();
const connString ="DRIVER {DB2};DATABASE=dbname;HOSTNAME=hostname;PORT=50000;PROTOCOL=TCPIP;UID=userid;PWD=password;CurrentSchema=schema;"
pool.init(5,connString);
pool.setMaxPoolSize(appConstants.db.dbConnectionPoolSize);

// This is how our code is to get query result:
public executeDBQuery(
    connQuery: string,
    paramList?: (string | number)[]
  ): any {
    return new Promise(async (resolve, reject) => {
      const connString = "DRIVER {DB2};DATABASE=dbname;HOSTNAME=hostname;PORT=50000;PROTOCOL=TCPIP;UID=userid;PWD=password;CurrentSchema=schema;";
      try {
        await pool.open(connString, async (connError: string, connection) => {
          if (connError) {
            reject(connError);
          } else {
            try {
              await connection.prepare(connQuery, (prepareErr, stmt) => {
                if (prepareErr) {
                  if (stmt) {
                    stmt.closeSync();
                  }
                  reject(prepareErr);
                } else {
                  stmt.execute(paramList, (executeErr, result) => {
                    if (executeErr) {
                      stmt.closeSync();
                      reject(executeErr);
                    } else {
                      result.fetchAll({ fetchMode: 4 }, (fetchErr, data) => {
                        if (fetchErr) {
                          reject(fetchErr);
                        } else {
                          console.log("DATA:" + JSON.stringify(data));
                          resolve(data);
                        }
                        stmt.closeSync();
                        result.closeSync();
                      });
                    }
                  });
                }
              });
            } catch (err) {
              reject(err);
            } finally {
              try {
                await connection.close();
              } catch (err) {
                reject(err);
              }
            }
          }
        });
      } catch (err) {
        reject(err);
      }
    });
  }
```

Before DB Server was down:
DATA: [{"COUNT":0}]

When DB server went down got an error:
[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "::1".  Communication function detecting the error: "recv".  Protocol 
specific error code(s): "*", "*", "0".  SQLSTATE=08001

After DB Server was up:
DATA: []

Note: Node server was up all the time.
Node version : 12.18.0
ibm_db : 2.6.4
platform : Both Windows and Linux.

**Comment by bimalkjha** [comment]
@Akash-H Application need to get a new connection by calling pool.open() when application gets SQL30081N error. You should get SQL30081N from connection.prepare(). 
Similar issue was discussed in #474 . Please go through it for help. Thanks.

**Comment by Akash-H** [comment]
@bimalkjha Thanks for the response.
I went through the issue which you mentioned. I understood what was the conclusion.
Currently we have different database instances that is selected at run time. We are running our project in container.
For dev, we have different database and for prod we have different database but docker image used is same.
How can we resolve this problem?

**Comment by bimalkjha** [comment]
@Akash-H If you use `ibm_db@2.7.0` and handle `SQL30081N` error in your application code, it should work fine for your scenario also. You need not to configure db2dsdriver.cfg file and hard-code the connection info.
Add check for SQL30081N in prepareErr. After getting SQL30081N, call executeDBQuery again.
You should also call `connection.close()` after `else` block of `if (prepareErr) {` so that connection can be returned back to pool and get available by another call of pool.open(). Thanks.

**Comment by Akash-H** [comment]
@bimalkjha I tried the upgrading ibm_db to 2.7.0 and called executeDBQuery on SQL30081 error from the application. It wait till it gets connected again but it doesn't get connected and incoming request gets terminated after 2 minutes. For next call it returns empty result. Thank you.

**Comment by bimalkjha** [comment]
@Akash-H We have a test program [ibm_db/test/test-bad-pool-connection-issue-42.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-bad-pool-connection-issue-42.js) to test this schenario. You can update database connection information in `test/config.testConnectionStrings.json` file and execute `node test-bad-pool-connection-issue-42.js` command after updating the time interval at last line of this file. We can make the pooled connection invalid by restarting the db2 server. Once db2 server restarts, all previous connection becomes invalid and ibm_db returns SQL30081N error.
I would request to share similar test program to reproduce your scenario that will help us to find the root cause. Thanks.
