### ISSUE TITLE
ibm_db license issue connecting to System Z

### ISSUE THREAD

**Issue by steven-ponessa** [ibmdb/node-ibm_db#684]
I am an IBMer working on an internal IBM application.  I need my Node.js API server to connect to an instance of DB2 on System Z but am getting licensing issue:
`SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 sqlcode:-1598`

It appears that placing `db2consv_zs.lic` in my `node_modules/ibm_db/installer/clidriver/license` folder might resolve the issue, however, running on a Mac, I am can not seem to find how I can get this file.

**Comment by bimalkjha** [comment]
@steven-ponessa db2consv_zs.lic is independent of platform. So, same file can be used on Windows and MacOS.
We have documented about license requirement here: https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity
Since you are IBMer, you can send email to connomon@us.ibm.com for db2connect license of version 11.5. Thanks.

**Comment by steven-ponessa** [comment]
Thank you.  This did resolve the db2connect license issue.
