### ISSUE TITLE
Can't get correct result when call store procedure in IBMDB2

### ISSUE THREAD

**Issue by manhha1006** [ibmdb/node-ibm_db#7]
In IBMDB2, I can't call procedure with type parameter is output. I always get result is null array

<pre><code>
---- Store Procedure SP_PROC1
CREATE PROCEDURE sp_proc1 (IN VARNAME VARCHAR(128), OUT VARCOUNT INTEGER)
P1: BEGIN
-- #######################################################################
-- # Returns count of tables created by ROOT and like VARNAME
-- #######################################################################
SELECT COUNT(*) INTO VARCOUNT FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'ROOT' AND NAME LIKE CAST('%'||VARNAME||'%' as VARCHAR(128));
END P1
</code></pre>

In the db2 studio I created store procedure and run test with input parameter VARNAME = "CA" and it return value with output parameter VARCOUNT = 3

code in nodejs

<pre><code>
conn.query("call ROOT.SP_PROC1(?,?)", ['CA',0] , function (err, rows, more) {
      console.log( err, rows, more );
      db.close(function () {
        console.log("Connection Closed");
      });
})
</code></pre>

console log

<pre><code>
null [] false
</code></pre>

so, how to handle bound parameters for output as I am intending to use here.

**Comment by mariobriggs** [comment]
RocketRooster is right. As we see more requests for out param support, we would like to take up that feature

**Comment by RocketRooster** [comment]
As it's turned out in my own framework, I don't want nor need out params, since I treat SP calls and SQL queries identically, it's made my code simpler :)

**Comment by wisewins** [comment]
Would this feature anytime be added ?

**Comment by zenflow** [comment]
Thanks @RocketRooster for your work-around. Worked great for me.

**Comment by zenflow** [comment]
Just to clarify and confirm - the best work-around we have right now is to (as @RocketRooster described) return output from the SP via cursors rather than "out params". You can wrap an existing SP to use this interface, as I've done.

@bimalkjha Are there any plans yet to implement "out param" support?

(In my case, I am working with a legacy database with many stored procedures that use "out params" and I need to call them through this module. The work-around of wrapping each one works, but is less that ideal :smiley:)

**Comment by bimalkjha** [comment]
@manhha1006 @zenflow OUT param support is added in ibm_db@1.0.1. Please see the test files mentioned here about usage: https://github.com/ibmdb/node-ibm_db#callStmt Thanks.
