### ISSUE TITLE
Unable to find the db2diag.log file

### ISSUE THREAD

**Issue by NikolasMcGovern-IBM** [ibmdb/node-ibm_db#704]
I am trying to find the `db2diag.log` file in order to help debug a `The specified library "" could not be loaded.` error. I am checking for the log file under `node_modules/ibm_db/installer/clidriver/db2dump` and running `testODBCConnection.sh` states that `db2diag.log Path` is the same path as above. When I check at that path, it does not seem to exist however. 

What causes this log file to generate? Why might I be unable to find it?

**Comment by bimalkjha** [comment]
@NikolasMcGovern-IBM Please share the name of OS on which you have installed `ibm-db`.
db2diag.log file gets generated if clidriver to hitting some area of code which logs data into db2diag.log file. If everything is working fine and in case of error, the code is not writing anything to db2diag.log file, it will be empty or do not exist at all.
I would suggest to share the result of `testODBCConnection.sh` and the generated files to investigate the root cause of the issue. The `1.fmt` file has all details about the issue and db2diag.log do not have always an entry.
You can create an empty `db2diag.log` file too if it do not exist and have correct permission set to avoid any permission issue. Actually, if you have installed ibm_db in a directory where user do not have permission to create a file, clidriver may fail to create the `db2diag.log` file. So, please check for the permissions too. Thanks.
