### ISSUE TITLE
Bulk Insertion of Array in Stored Procedure

### ISSUE THREAD

**Issue by manasa094** [ibmdb/node-ibm_db#717]
Similar to bulk array insert, is it possible  to pass bulk array data as an input parameter to Stored Procedure as follows:
var param1 = {ParamType:"ARRAY", DataType:1, Data:["row 1","first row","aaa","bb"]};
  var param2 = {ParamType:"ARRAY", DataType:1, Data:["row 2","test1","qq","true"]};
  var param3 = {ParamType:"ARRAY", DataType:1, Data:["row 3","test2",,"uu","true"]};

  var queryOptions = {sql:"CALL ARRAYPROCEDURE(?,?,?,?)", 
                      params: [param1, param2, param3],
                      ArraySize:3};

**Stored Procedure Definition:**
CREATE OR REPLACE PROCEDURE ARRAYPROCEDURE(
                IN COL_1 VARCHAR(25),
		IN COL_2 VARCHAR(25),
		IN COL_3 VARCHAR(25),
		IN COL_4 VARCHAR(25),
		)
LANGUAGE SQL
 BEGIN
 …
 END

@bimalkjha - Can you please help me with this.

**Comment by bimalkjha** [comment]
@manasa094 Yes, it should work. But, you need to modify param1,2, 3 . Pass `Length` too else character data larger than size of first array element will get truncated. You second array element is of 8 bytes, so I would suggest to set the param1 as below:
```
var param1 = {ParamType:"ARRAY", DataType:1, Length: 8, Data:["row 1","first row","aaa","bb"]};
```
Also, you need to use `ArraySize:4` in `queryOptions` as size of Data array is 4 for param1 and param2.
Correct you param3 data, it has two comma after second element which makes it an array of size 5.
Please share your test result here. Thanks.

**Comment by manasa094** [comment]
@bimalkjha - I tried the same above mentioned process and facing this error.

_**Error:**_ [IBM][CLI Driver][DB2/LINUXX8664] SQL0301N  The value of input variable, expression or parameter number "1" cannot be used because of its data type.  SQLSTATE=07006

The code and the stored procedures used are below.
**_Code:_**
const param1= { ParamType: "ARRAY", DataType: 1, Data: [1, 2, 3] } ;

let queryOptions = {
          sql: "CALL  ARRAYPROCEDURE(?)",
          params: [param1],
          ArraySize: 3
        };
        conn.queryResult(queryOptions, (err, result) => {
         if(err){
           console.log(err);
            }
          } 

**_Stored Procedure:_**
CREATE OR REPLACE PROCEDURE  ARRAYPROCEDURE (
IN pARRAY INTEGER_ARRAY;
)
BEGIN
.....
END

**_INTEGER_ARRAY Definition:_**
  CREATE TYPE  INTEGER_ARRAY AS INTEGER ARRAY[100];

**Comment by bimalkjha** [comment]
@manasa094 In your above shared case, just remove "ArraySize: 3" from `queryOptions` and run your test program. It should work. Thanks.

**Comment by manasa094** [comment]
@bimalkjha- After making the above mentioned change the code error was resolved but only the first index value in the array is getting passed into the SP.
const param1= { ParamType: "ARRAY", DataType: 1, Data: [1, 2, 3] } ;

Tried Passing the above param into the SP but only the first index (1) is getting to pARRAY variable.(2 and 3 value are not binded )

**Comment by amigosrishti539** [comment]
@bimalkjha Event I am facing the same issue as above. I am trying to pass the below params into the SP for bulk insertion:
const param1= { ParamType: "ARRAY", DataType: 1, Data: [100,100,200] } ;
const param2= { ParamType: "ARRAY", DataType: "INTEGER", Data: [1,2,3] } ;

But only the first indexes of the array i.e. ONLY 100 and 1, are getting passed to the SP; not all the array elements. Is there some way of fixing this issue ?

**Comment by bimalkjha** [comment]
@manasa094 Let us know your result.
@amigosrishti539 Array insert in only supported for INSERT statements. You can define SP arguments as array and pass arrays while calling the SP, but to insert data within the SP, you need to extract every field from the Array inside SP and pass only one value in the insert statement.  I would suggest to first verify that your SP works from DB2 CLP command prompt or DB2 ODBC driver and then try calling it from `ibm_db`.
See [this documentation](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.sqlpl.doc/doc/c0052894.html) for more info about Array Support in SP:
`Within SQL stored procedures, arrays can be manipulated as arrays in conventional programming languages.` Thanks.

**Comment by Yusuf023** [comment]
@bimalkjha 
Copying my question from issue #668 since that issue is closed.

I was trying to do a proof of concept by passing a User-defined array data type from NodeJS to the Stored Procedure.

Table, User-Defined Type, and SP Definition:

CREATE TABLE ABC.LAB_INSERT_TEST_3 (
INSERT_TEST_3_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
PHONE_NUMBER BIGINT
);

CREATE TYPE "ABC"."BIGINT_ARRAY" AS BIGINT ARRAY [50];

CREATE OR REPLACE PROCEDURE ABC.INSERT_ARRAY_TEST (
IN pARR ABC.BIGINT_ARRAY)
BEGIN

INSERT INTO PORTAL.LAB_INSERT_TEST_3(PHONE_NUMBER)
SELECT AR.PHONE_NUMBER
FROM
UNNEST(pARR)AS AR(PHONE_NUMBER);
END

From Node Js, the following promise is getting called:

export const insertTest = async () => {
return new Promise((resolve, reject) => {
const queryString = `CALL ABC.PORTAL.INSERT_ARRAY_TEST(?)`;
let arr = [124, 125, 126];
let queryOptions = {
sql: queryString,
params: [
{
ParamType: "ARRAY",
DataType: "DOUBLE",
Data: arr,
Length: arr.length
}
],
noResults: true,
ArraySize: arr.length
};
ibmdb.open(global.dbConnectionString, (error, conn) => {
if (error) {
reject("Error when opening connection: " + error);
} else {
conn.query(queryOptions, err => {
if (err) {
console.error(err);
reject(err);
} else {
resolve();
}
conn.close();
});
}
});
});
};

I'm not getting any SQL Error and the Promise is getting resolved. However, no insertion is taking place. I've tried changing the DataType property to BIGINT or omitting it but it didn't work.
Can you please help me as to what might be going wrong?
Thanks.

**Comment by Yusuf023** [comment]
@bimalkjha Is there any update on this?

**Comment by bimalkjha** [comment]
@Yusuf023 Are you able to execute these SQL using any other client against Db2? Using ODBC or JDBC or any other client? If yes, could please share that example? Thanks.

**Comment by bimalkjha** [comment]
@Yusuf023 I have added a test file to show how to insert an array in a table using Stored Procedure and how to pass array to stored procedure. Please refer [this test file](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-array.js) to see it and modify your application accordingly.
You can execute this file after updating connection string in `test/config.testConnectionStrings.json` file. Let me know if you are still facing any issue. Thanks.
