### ISSUE TITLE
 TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by deidrap** [ibmdb/node-ibm_db#724]
Error when using ibm_db on Node.js 14.9.0 (Windows 10) with React.js

I have some basic javascript code that uses React.js.  As soon as I require('ibm_db'), I get a runtime error when running 'npm start'. The error comes from bindings.js and is attached. I think it is a conflict with the Error object.
I don't know if there is a workaround but would love to know.

![Error captureStackTrace](https://user-images.githubusercontent.com/24275653/100750469-125ac300-33b4-11eb-95c9-890ae92c4900.jpg)

Thank you.

**Comment by bimalkjha** [comment]
@deidrap The Error object is an inbuilt object of node.js and `bindings` module is just using it. You can not see its definition in `bindings.js`. Just type `node` on your command prompt and then type `Error`, you can get output as below:
```
/home/bjha> node
Welcome to Node.js v14.9.0.
Type ".help" for more information.
> Error
[Function: Error] { stackTraceLimit: 10 }
> 
```
I just googled about `Error function of node.js` and got - 
* The first thing to know about Node. js error handling is the error object. ... The error object is an implementation of a constructor function that uses a set of instructions (the arguments and constructor body itself) to create an object. That's it.

Check https://nodejs.org/api/errors.html for more info. So, you need to handle it in your application or you need to find a way to avoid it. You can get this error by executing `var a = require('bindings')` command on node prompt in your environment.
Since, this issue is not related with `ibm_db`, I am closing it. Thanks.

**Comment by deidrap** [comment]
I'm not sure you are understanding. This is not about me not understanding
how error handling works.

To recreate the problem, do the following.

1. Create a simple React application on node.js (do you want me to send you
code?).
2. Add require('ibm_db')  (assuming npm install ibm_db has already been
called)

You will see the stacktrace error. There is some kind of conflict.

Let me know if you would like me to send you example programs. Can you
please reopen this.

Deidra Picciano
Cloud and Cognitive Software - Chief Data Office
Slack: @deidrap
deidrap@us.ibm.com

**Comment by bimalkjha** [comment]
@deidrap The code that you mentioned is from bindings.js which is form `bindings` package of node.js and not `ibm_db`. ibm_db is just a user of `bindings` package. I think you'll get the same issue when you do `requrire('bindings')` too. So, if you think the code of bindings.js is incorrect, I would suggest to open an issue here: https://github.com/TooTallNate/node-bindings/issues

Yes, please share react code so that I can reproduce the issue and get more info. Thanks.
