### ISSUE TITLE
DB2 connection not working in Google Cloud function

### ISSUE THREAD

**Issue by pweisensee** [ibmdb/node-ibm_db#735]
I'm having connection issues running this library from a Google Cloud serverless function using Node.js 10 and 12 on Ubuntu 18.04.

Does installing the library on my local machine (MacOS Catalina) mean that the proper ODBC driver is also deployed to the cloud function runtime environment? Is it impossible to use this library in a serverless function? Does IBM support this with their cloud services?

```
[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "192.168.0.100".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001
```

```
const connectionString = "DATABASE=example;UID=username;PWD=password;PORT=50000;PROTOCOL=TCPIP;HOSTNAME=192.168.0.100;"

await ibmdb.open(connectionString, function (connectionErr: any, connection: any) {
    if (connectionErr) {
        reject(connectionErr?.message || JSON.stringify(connectionErr));
    } else {
        connection.query(
            'select 1 from sysibm.sysdummy1',
            function (queryErr: any, data: any) {
                if (queryErr) {
                    reject(queryErr?.message || JSON.stringify(queryErr));
                } else {
                    connection.close(function () {
                        console.log('done');
                    });
                    resolve(true);
                }
            }
        );
    }
});
```

**Comment by bimalkjha** [comment]
@pweisensee Yes, installing the library on your local machine (MacOS Catalina) mean that the proper ODBC driver is also deployed with the ibm_db library on your local machine. 
It is possible to use this library in a serverless function.
The purpose of this library is to provide connectivity with Db2 database where database exists locally or remotely or on cloud.
Looking on your connection string and error, it seems there is timeout error while connecting to a remote database. Verify your connection string, make sure database is up for connection and still getting same error, then add connection timeout in ibmdb.open as below:
```
await ibmdb.open(connectionString, { connectTimeout : 120}, function (connectionErr: any, connection: any) {
```
I think your database is unable to provide connection within 30 seconds. May be due to slow network or host system. Default value of connection timeout is 30 seconds, so increasing it to 2min should work. Thanks.

**Comment by bimalkjha** [comment]
@pweisensee Let us know if you are still facing the issue using connectTimeout parameter. Else, please close the issue. Thanks.

**Comment by pweisensee** [comment]
Yes, I tracked down the issue to the PORT, and then discovered we lacked the proper licensing from IBM. Still working on it, but you answered my question. Thanks for clarifying.
