### ISSUE TITLE
Conversão charset

### ISSUE THREAD

**Issue by GilbertoTADS** [ibmdb/node-ibm_db#739]
Tenho app em NODE que faz requisições no banco de dados db2 via ibm_db. Porém, no retorno dos dados todos os caracteres acentuados e ç é convertido para �.

Obs: Confirmei o charset do banco de dados via charset-detector, ele me retornou:
`CharsetMatch {
    confidence: 15,
    charsetName: 'UTF-8',
    lang: undefined
  },
  CharsetMatch { confidence: 10, charsetName: 'Shift_JIS', lang: 'ja' },
  CharsetMatch { confidence: 10, charsetName: 'GB18030', lang: 'zh' },
  CharsetMatch { confidence: 10, charsetName: 'EUC-JP', lang: 'ja' },
  CharsetMatch { confidence: 10, charsetName: 'EUC-KR', lang: 'ko' },
  CharsetMatch { confidence: 10, charsetName: 'Big5', lang: 'zh' }
]`

Nota 1: Quando eu crio uma string com acentos e ç tudo é apresentado normalmente.

Nota 2:  Tentei substituir os caracteres com acentos e ç pelos sem acento e c via query -> `SELECT TRANSLATE (pv.DESCRICAOPRODUTO,'AÇEIOUAEIOUAEIOUAOEUIONY ','ÁCÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜÏÖÑÝº') AS DESCRICAOPRODUTO from [...TABELA...]...continua....` o problema continuo (Na própria base de dados a query funciona).

Nota 3: também tentei (num ato de desespero), converter o charset para utf-8 no NODE, também sem sucesso

Aparentemente o problema ocorre entre o Node e o DB2.
Como posso diagnosticar e resolver isso?

Se quiserem conferir o código, segue o link do repositório: https://github.com/GilbertoTADS/botmaker-chat.git

**Comment by bimalkjha** [comment]
@GilbertoTADS Login to your Db2 server system and execute below commands assuming DBNAME is the name of your database:
```
db2 connect to DBNAME
db2 get db cfg
db2 terminate
```
Please share the complete output of "db2 get db cfg" command. You can check value of "Database code page". Probably its not 1208. To get the accented chars well via ibm_db, set environment variable `DB2CODEPAGE=1208` in the system where ibm_db is installed. You can also add a line `process.env.DB2CODEPAGE = 1208;` in your application before calling `ibmdb.open` API.
Your issue is similar to issue #614 , you can check it for more info. Thanks.

**Comment by GilbertoTADS** [comment]
Ao executar os passos recomendados, vi que de fato DB2CODEPAGE não era 1208. Apenas essa alteração resolveu meu problema. Muito obrigado! Abraços!
