### ISSUE TITLE
 Concurrent asynchronous query execution fails when application is hosted on IBM Cloud

### ISSUE THREAD

**Issue by SapnaGirdhani1** [ibmdb/node-ibm_db#745]
Concurrent asynchronous query execution fails when application is hosted on cloud. In such case, first query works fine , from second query onwards results are not as expected. I am attaching a document with more details.
[NodeJs-DB2.docx](https://github.com/ibmdb/node-ibm_db/files/6020003/NodeJs-DB2.docx)

Note - such queries work well when the application is running on local machine while the DB2 is still hosted on Cloud. But it fails if both -application and DB2 instance are cloud hosted.

**Comment by bimalkjha** [comment]
@SapnaGirdhani1 The screenshot is from which table? sys_survey or sys_email_template? Please share the create table SQL too from that table. Also, share the Operating System name of your local system.
The problem looks only with second column and difference is due to difference is operating system used locally vs cloud. I think OS in cloud is Linux.
Please share Create table SQL and Insert statement for the table having corrupted data. Also, what type of data is getting inserted and what is the parameters. A small node.js test program would be helpful the find the root cause of the issue. Thanks.

**Comment by SapnaGirdhani1** [comment]
Screenshot is from sys_email_template table. In the query sequence, first query fired to sys_survey table and worked well. 
Second query fired to sys_email_template where junk data got inserted for surveyId column.

In my local machine, OS is - Windows 10. 

CREATE TABLE "sys_email_template" (
  "surveyId" varchar(36) NOT NULL DEFAULT '',
  "userType" varchar(50) NOT NULL DEFAULT '',
  "subject" varchar(256) NOT NULL DEFAULT ''
   PRIMARY KEY ("surveyId","userType")
) ;

Insert Query:
 INSERT INTO "sys_email_template" ("surveyId", "userType", "subject") VALUES(?, 'respondent', 'Baseline Survey')"
 
Where "surveyId" is passed using binding parameters. 
This is just one example. There are other scenarios also with concurrent query execution, where only first query is working and from second query onwards it fails. In another scenario 1st query is an INSERT query and second query is a SELECT query. So I get empty array as a response from SELECT query. However query works well from Windows OS. 

Just to add, in both the cases my DB2 is hosted on Cloud, it is just application which is hosted in two environments - Local (Windows) and Cloud.  
Regarding sample node js program, I'll try to create one. Thanks !

**Comment by bimalkjha** [comment]
@SapnaGirdhani1 Thanks for sharing the `create table` sql. Please share the binding parameter syntax too for "surveyId". It works fine for me and you too mentioned that it works for you when ibm_db is installed locally. It might be due to the way, the datatype in bind parameter is used. 
Also, the corrupted data looks integer data. So, I would suggest to use latest version of `ibm_db@2.7.4` and try as we have fixed few issues related to BigInt and Decimal data in latest release.
If it does not work, then cd to ibm_db\test directory and run your application using `trace full_path_of_app.js` where app.js is your application. If application do not terminate automatically, then run `db2trc off` after killing the application.
It'll generate binary dump file and db2 traces. Please share those generated files for analysis. Thanks.
