### ISSUE TITLE
Unexpected truncation of data with query string (adding array)

### ISSUE THREAD

**Issue by ScottJRoberts** [ibmdb/node-ibm_db#752]
Adding multiple items using the query string format of 

`let queryOptions = { sql: sql, params: paramsArray, ArraySize: batchSize };
let results = await conn.query(queryOptions);
`
is truncating all of the datafields that are shorter than the first item in the paramsArray.

example:

`const fake_param_array = [
  {
    ParamType: "ARRAY",
    DataType: "VARCHAR(120)",
    Data: [
      "this is a short description",
      "this is a longer description ponder please",
    ],
  },
  {
    ParamType: "ARRAY",
    DataType: "VARCHAR(120)",
    Data: ["101001001010", "100101001000088888888"],
  },
];`
`const fake_batch_sql = "insert into TEST.TEST_TABLE (DESC, ID) values (?, ?)"`

`let queryOptions = { sql: sql, params: fake_params_array, ArraySize: 2 };
 let results = await conn.query(queryOptions)
`

the table is then populated with the following 

`[
  { DESC: 'this is a short description', ID: '101001001010' },
  { DESC: 'this is a longer descriptio', ID: '100101001000' }
]`

The makeup of the table:

`{
  desc: { COLNAME: 'DESC', TYPENAME: 'VARCHAR', LENGTH: 120 },
  id: { COLNAME: 'ID', TYPENAME: 'VARCHAR', LENGTH: 120 }
}`

Both fields are lower than the maximal allotted amount in the table, but having the first one have a shorter field cuts off the rest of the following

**Comment by bimalkjha** [comment]
@ScottJRoberts Your observation is correct. It happens due to missing Length keyword in param object. If we do not use Length keyword, then length of first element is assumed as length of every member of array. We have documented it in [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#bindParameters) for ARRAY as below:

ARRAY - It tells the Data is an Array of same type and size. It must be used for Array Insert i.e. to insert data for multiple rows using single execute. If one parameter is of type ARRAY, all parameters passed to an API must be of type ARRAY and of equal size. Check test/test-array-insert.js for example. Use "**Length**: " in param Object for unequal size of data. Default value is the length of first member of Array.

So, your code should be as below:
```
const fake_param_array = [ { ParamType: "ARRAY", DataType: "VARCHAR(120)", Data: [ "this is a short description", "this is a longer description ponder please", ], Length: 50 }, { ParamType: "ARRAY", DataType: "VARCHAR(120)", Data: ["101001001010", "100101001000088888888"], Length: 50 }, ];
```
Use of Length should fix your issue. So, closing it. Thanks.
