### ISSUE TITLE
SSL connection is not working even though I provided arm cert into SSLServerCertificate

### ISSUE THREAD

**Issue by amarm85** [ibmdb/node-ibm_db#762]
Hi, 

I am trying to connect to DB2 server over SSL port . I got the arm cert using command 
`openssl s_client -showcerts -connect db2severurl:sslport` I copied the cert into one file and used that in my code ..

`DRIVER={DB2};DATABASE=${config.dbname};UID=${config.userid};PWD=${config.password};HOSTNAME=${config.hostName};port=${config.SSLport};Security=SSL;SSLServerCertificate=${config.SSLServerCertificate};`

But  I still get error 

```{ [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Locatio
n where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001
]
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -30081,
  message:
   '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location wher
e the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001\r\n',
  state: '08001' }
```

```
$ node --version
v10.16.0
```

**Comment by bimalkjha** [comment]
@amarm85 It looks your certificate is not correct. The 414 error in case of SSL connection is a gskit error which tells certificate file is incorrectly formatted and there is some issue with the certificate file. Either it is not generated correctly on server or it got generated using some old gskit version installed on server. [This](https://stackoverflow.com/questions/53609339/error-when-connecting-to-db2-with-ibm-db-with-ssl#:~:text=A%20stash%20file%20generated%20with,that%20the%20client%20is%20using.) stackoverflow post has more details. Please go through it and get correct certificate file. Your connect string is correct and it should work with correct certificate file. Thanks.

**Comment by Sridharv-ec** [comment]
Hi @bimalkjha ,
Good to have you in the chat. If you remember, I had a query on the IBM_DB code in the previous chat which we discussed in the below link. I am unable to comment further so I am commenting in the below link because its locked to add further comments . So I am asking you in this chat. I am facing this issue in the windows machine. 
https://github.com/ibmdb/node-ibm_db/issues/393

I am able to generate the certificate files using following commands.
keytool -importkeystore -srckeystore my_cert.jks -destkeystore my_cert.p12 -deststoretype PKCS12

openssl pkcs12 -in my_cert.p12 -clcerts -nokeys -out my_cert.crt

openssl pkcs12 -in my_cert.p12 -nokeys -out my_cert_full.crt

I am able to generate the certificate files in .crt and .pem extension. When I use the certificate generated from the above commands in the below code, I am getting below error

----------------------------------------- code -------------------------------------------------------------------
   var connStr = 'DRIVER={DB2};DATABASE=MYDBASE;HOSTNAME=MYHOST;PORT=5654;PROTOCOL=TCPIP;UID=MYUSERID;PWD=MYPASSWORD';Security=SSL;SSLServerCertificate=C:/Lloyds/OB/GHE1/aisp-e2e-bdd/test/certificates/db2/DGSCATST_CERT_JS_NEW_1.crt';
   

    ibmdb.open(connStr, function (err,conn) {
        if (err) return console.log(err);
                
            conn.query("SELECT * FROM MYTABLE WHERE SESSION_ID = 'd1992c73-9e6a-4367-9885-a5cd176e5519'", function (err, data) {
            if (err) console.log(err);
            else console.log(data);
              
            conn.close(function () {
            console.log('done');
           });
        });
    });

--------------------------- Error-----------------------------------------------------------------------------
[0-0] [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001
[0-0] ] {
[0-0]   error: '[ibm_db] SQL_ERROR',
[0-0]   sqlcode: -30081,
[0-0]   state: '08001'
[0-0] }
-----------------------------------------------------------------------------------------------------------------------------

You had suggested to generate the certificate using below commands but I am unable to install the GSKIT software from the IBM portal because its not allowing to download it. Can you please help us? 
https://www.ibm.com/support/fixcentral/swg/selectFixes?product=ibm/Tivoli/IBM+Global+Security+Kit&function=fixId&fixids=8.0.14.*-GSKIT-WinX64*

gsk8capicmd_64 -cert -extract -db "/home/bimaljha/ssl/server.kdb" -pw "keydbpasswd" -label "MyClientCert" -target "/home/bimaljha/ssl/server.arm" -format ascii -fips

If it doesn't work ,then generate .crt file using below command:

gsk8capicmd_64 -cert -extract -db server.kdb -pw "keydbpasswd" -label "MyClientCert" -target myselfsigned.crt -format ascii

**Comment by bimalkjha** [comment]
@Sridharv-ec The certificate for client should get generated from Db2 server system. If you have installed Db2 server, the GSKit libraries also get installed with Db2 server. You need to generate client certificate using the `gsk8capicmd_64 ` command shared in my previous post. So, I understand that you have installed ibm_db on Windows system, but on which Operating System, your Db2 sever is installed? The client certificate need to be generated from keystore database of Db2 server using GSKit commands, not using the openssl or keytool command. Also, the server must be configured using the keystoredb and stash file/password to accept the client connection request. SSL Port must be enabled on server. So, you need to generate .arm certificate on Db2 server system, not on the system where you are installing ibm_db. Thanks.

**Comment by Sridharv-ec** [comment]
Thanks for your suggestion @bimalkjha 

The DB2 server is not installed in my machine because of restrictions my client machine. I have got the DB2 details from the environments team. 
We had got the certificate in the .JKS format which we used it for java application and working fine in java.

We are able to generate the certificate in .arm / .pem / .cer extension from the same .JKS file which I have it.
Can't we use the certificate in .pem / .arm/ .cer generated from the same .JKS which I already have it using following commands?

keytool -importkeystore -DGSCATST.jks -destkeystore my_cert.p12 -deststoretype PKCS12

"C:\Program Files\Java\jdk-11.0.12\bin\keytool.exe" -list -v -keystore my_cert.p12 -storetype PKCS12

winpty openssl pkcs12 -in my_cert.p12 -clcerts -nokeys -out DGSCATST_CERT_JS_NEW.pem

winpty openssl pkcs12 -in my_cert.p12 -nokeys -out DGSCATST_CERT_JS_NEW_2.arm

When I use the certificate in the .pem/ .arm / .cer extension generated from the above commands and execute the IBM_DB code I am still getting below error

[0-0] Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001
[0-0]
[0-0]     at Database.openSync (C:\Lloyds\OB\GHE1\aisp-e2e-bdd\node_modules\ibm_db\lib\odbc.js:415:26)
[0-0]     at Function.openSync (C:\Lloyds\OB\GHE1\aisp-e2e-bdd\node_modules\ibm_db\lib\odbc.js:151:6)
[0-0]     at db2Connect1 (C:\Lloyds\OB\GHE1\aisp-e2e-bdd\test\stepDefinitions\/aisp_api_steps.js:172:34)
[0-0]     at World.<anonymous> (C:\Lloyds\OB\GHE1\aisp-e2e-bdd\test\stepDefinitions\/aisp_api_steps.js:168:8)
[0-0]     at World.executeAsync (C:\Lloyds\OB\GHE1\aisp-e2e-bdd\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\shim.js:101:25)
[0-0]     at World.exports.testFrameworkFnWrapper (C:\Lloyds\OB\GHE1\aisp-e2e-bdd\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:18:32) {
[0-0]   error: '[ibm_db] SQL_ERROR',
[0-0]   sqlcode: -30081,
[0-0]   state: '08001'

Please find the connection string below. If there anything missing?

var connStr = 'DRIVER={DB2};DATABASE=MYDB;HOSTNAME=MYHOST;PORT=MYPORT;PROTOCOL=TCPIP;UID=MYUID;PWD='MYPASSWORD';Security=SSL;SSLServerCertificate=C:/Lloyds/OB/GHE1/aisp-e2e-bdd/test/certificates/db2/ca-jenkins-slave-appduv327a-DGSCATST.cer';

**Comment by bimalkjha** [comment]
@Sridharv-ec The error code 414 means GSK_ERROR_BAD_CERT which tells that your certificate file is wrong. More details about 414 error can be found here: https://www.ibm.com/docs/en/db2/11.5?topic=troubleshooting-common-gskit-errors
```
GSKit: 414

This return code indicates that an incorrectly formatted certificate was received from the partner in an TLS relationship.
This error can be returned in these scenarios:

    You are using self-signed certificates and the certificate is missing.
    The certificate that is being used is from a local certificate authority that does not have the Basic Constraints extension active. 
```
I would suggest to get the .arm certificate from the environment team. The certificate file must be generated using gskit command as shared in my previous post from the Db2 server system. Thanks.

**Comment by Sridharv-ec** [comment]
Thanks a lot @bimalkjha for your response. 
I am just finding out from where I can get DB2 Server. I am using windows machine only. The DB2 credentials which I have is not mine. Its is used for development / automation testing. If you share the steps to install DB2 server then it will be useful.
Thanks

**Comment by bimalkjha** [comment]
@Sridharv-ec The certificate must get generated on the same Db2 server with which you want to establish SSL connection. So, if your environment team has shared Db2 server connection info, you need to get .arm file from environment team only. If your intention is to not use the connection info shared by environment team or do not connect to the Db2 server pointed by environment team, then you can install your own Db2 server in windows and do the SSL setup by following IBM documentation. You can get the Db2 server installer for Windows from your environment team only. Other method is by contacting IBM Support or download from IBM Passport Advantage. I think only customers registered with IBM can download Db2 Server image from IBM Passport advantage. So, better to go with your environment team only. Thanks.
