### ISSUE TITLE
Connect nodejs IBM Function to db2 zOS, with license

### ISSUE THREAD

**Issue by juanitodur** [ibmdb/node-ibm_db#771]
Hello,

I have a nodejs IBM Function action. I need to connect to our db2 zOS. We have the license. If we execute the code on our backend with the .lic file in the corresponding directory, there is no problem. However, on Functions, we don't have a path to place the file. Is there a way do acheive this?

Thanks

**Comment by bimalkjha** [comment]
@juanitodur Please provide more info about - `However, on Functions, we don't have a path to place the file.`
We need to copy license file under `ibm_db\installer\clidriver\license` directory or `clidriver\license` directory if IBM_DB_HOME env var is set. After that if you call any ibm_db.open() or openSync() API, license automatically gets picked up from that location.
If you have written any wrapper around ibm_db, you need to write code to copy license file under `clidriver\license` directory before importing ibm_db. Thanks.

**Comment by bimalkjha** [comment]
License file should get copied to `clidriver\license` directory post installation of `ibm_db` and before `import ibm_db`. Thanks.

**Comment by juanitodur** [comment]
Hi! I am aware of the path to where we need to place the license file. However, and I am not sure if you are familiar with IBM Functions (based on Apache OpenWhisk) and serverless model), there is no directory to where we can put it, or at least, using the web UI, this is something we can't do by just simply dropping it somewhere.

**Comment by bimalkjha** [comment]
@juanitodur I do not know internals of IBM Functions and how it is using ibm_db? If you can throw some light on the usage or some example, that would be helpful.
There must be some step which installs ibm_db in cloud environment and then the IBM Function code access it. So, how and when `ibm_db` get installed by the Function and which command or script install it? You need to modify that script or code to copy the license file into license directory post installation of ibm_db.
For example, when an application get deployed on bluemix using `cf push` command, during the deployment of application ibm_db get installed. So, user keeps license file in application directory so that license file also get pushed to cloud along with application code. User updated the deployment code to copy the license file from application directory to license directory post installation of ibm_db. You should use similar logic here. Thanks.

**Comment by lukas12691** [comment]
Hi guys, facing a similar issue with license ` [Error: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`. But I have not idea what I am doing wrong. License has been already copied to the node_modules/ibm_db/installer/clidriver/license folder. Permissions set to 755. Clidriver v11.5 and license v11.5. For ssl connection used SSLClientKeystoredb and SSLClientKeystash. Thanks a lot in advance.

**Comment by bimalkjha** [comment]
@lukas12691 Update database connection info in `ibm_db\installer\testODBCConnection.sh` or `testODBCConnection.bat` file based on your platform for `db2cli validate` command in the script. Add `-displaylic` option at the end of `db2cli validate` command in the script file. Run the script and share complete output of the script in a new issue.
By looking on script output, you should be able to figure out the problem. Else, please open a new issue with details including platform name. Thanks.
