### ISSUE TITLE
'Cannot find module' in Jest integration

### ISSUE THREAD

**Issue by lhimo** [ibmdb/node-ibm_db#773]
I'm trying to import the ibm_db module into Jest framework, but I'm getting the following error:

      Cannot find specified module.
      <path to repo>\node_modules\ibm_db\build\Release\odbc_bindings.node

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:991:29)
      at bindings (node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (node_modules/ibm_db/lib/odbc.js:57:31)

The module was installed and loaded with `const ibmdb = require('ibm_db');`. Am I missing something?

**Comment by lhimo** [comment]
The file is there, executing the command gives:
```
Trying to open a connection ... 
 ... Got the connection.
insertedRows =  1
[ [ 1, 4, 5 ] ]
[]
Selected data with special character  =  [ [ 4, 'für', null ] ]
[ [ 3, 7, 8 ] ]
Inserted row count = 1
Column Names =  [ 'C1', 'C2', 'C3' ]
Column Meta Data =  [
  {
    index: 1,
    SQL_DESC_CONCISE_TYPE: 'C1',
    SQL_DESC_TYPE_NAME: 'INTEGER',
    SQL_DESC_DISPLAY_SIZE: 11,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 11
  },
  {
    index: 2,
    SQL_DESC_CONCISE_TYPE: 'C2',
    SQL_DESC_TYPE_NAME: 'VARCHAR',
    SQL_DESC_DISPLAY_SIZE: 10,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 10
  },
  {
    index: 3,
    SQL_DESC_CONCISE_TYPE: 'C3',
    SQL_DESC_TYPE_NAME: 'BLOB',
    SQL_DESC_DISPLAY_SIZE: 200,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 100
  }
]
Fetched Data =
[
  { C1: 4, C2: 'für', C3: null },
  { C1: 34245, C2: 'bimal', C3: null }
]
conn.querySync('select * from mytab1 where c1 = ?;', valueArray)
[ [ 34245, 'bimal', null ] ]
Result of UPDATE Query =  [ [], [ [ 1 ] ] ]
SQLCA =  { state: '0', sqlcode: 0 }
conn.prepare('delete from mytab1 where c1 = 89')
Deleted row count = 0
done
```

**Comment by bimalkjha** [comment]
@lhimo Since you are able to execute `test-basic-test.js` script, so ibm_db installation is proper and it is working fine. Your Jest env too have the *.js file, so it should work from that file too. May I know what is the path of your starting application?
It might be some env issue. So, if you are on windows system, add `<path to repo>\node_modules\ibm_db\installer\clidriver\bin;<path to repo>\node_modules\ibm_db\installer\clidriver\lib;` to PATH and LIB system environment variable. Then try from start. It should work. Thanks.

**Comment by lhimo** [comment]
It's still not working :( 

For the moment I'll be using mocha/chai instead of Jest

**Comment by bimalkjha** [comment]
@lhimo If it is working with mocha/chai but not with Jest, then there must be some environment related issue which is different for mocha and Jest. Since, it is working with mocha, so I do not see any issue with ibm_db. You need to tell what is the exact issue and how are you running. simply saying not working, does not give any info without any repro.
I just checked about Jest and found this link: https://www.browserstack.com/guide/jest-framework-tutorial
It says: **"Since Jest is a Selenium test framework and Selenium is built upon Java, and so testers have to get the installation done for the Java Development Kit on the system and then configure the system with the JAVA environment."**
So, this Java thing may be causing the problem as ibm_db do not use Java at all and it is platform dependent as it comes with some native code.
Thanks.

**Comment by lhimo** [comment]
I agree, I'll file an issue over at Jest repo. Thanks
