### ISSUE TITLE
Using "IBM_DB_INSTALLER_URL" for ibm_db with Python

### ISSUE THREAD

**Issue by sxnguyen** [ibmdb/node-ibm_db#792]
Hello,
I've been searching around and found that the "IBM_DB_INSTALLER_URL" is typically referencing NodeJS (npm) install.  Can you confirm if we can use this param for Python?
Thanks,
Scott

**Comment by bimalkjha** [comment]
@sxnguyen IBM_DB_INSTALLER_URL is part of node-ibm_db installer only. python-ibm_db has not implemented it. So, you can not use it for python ibm_db driver. Thanks.

**Comment by bimalkjha** [comment]
@sxnguyen Actually, you should use IBM_DB_HOME instead of IBM_DB_INSTALLER_URL for offline installation of ibm_db. There is no much difference between IBM_DB_HOME and IBM_DB_INSTALLER_URL. IBM_DB_INSTALLER_URL points to the clidriver.tar.gz file downloaded in the system but IBM_DB_HOME points to the untared directory clidriver.
So, you need to download clidriver.tar.gz, untar it and set IBM_DB_HOME env var pointing to the clidriver directory. Then you can install ibm_db driver. 
IBM_DB_HOME is supported by both node and python ibm_db driver. Thanks.
