### ISSUE TITLE
Issue with gsk8ssl_64.dll

### ISSUE THREAD

**Issue by crishmc** [ibmdb/node-ibm_db#802]
Hello! I'm programming in nodejs and running queries using ibm_db to access the DB2 in the Mainframe. 
I'm also using the ibmmq library to send data using MQ. 

Due this scenario, I have the DDL gsk8ssl_64.dll in 2 paths in my computer (It's windows): 
..\node_modules\ibmmq\redist\gskit8\lib64
..\node_modules\ibm_db\installer\clidriver\bin\icc64

When I try to connect to DB2 by an endpoint call (get or post), the dll found at \node_modules\ibm_db\installer\clidriver\bin\icc64 works fine. But when I try to connect to DB2 when the process is scheduled (using node-schedule) I receive the following error:

"The procedure entry point ?getPrivateKeyPtr@GSKKRYKeyPair@@QEBA?BV?$GSKCountedPtr@VGSKKRYKey@@@@XZ could not be located in the dynamic link library c:\xxxx\node_modules\ibm_db\installer\clidriver\bin\icc64\gsk8ssl_64.dll. "

If I copy the file gsk8ssl_64.dll from \node_modules\ibmmq\redist\gskit8\lib64 to \node_modules\ibm_db\installer\clidriver\bin\icc64, the connection is establish, but it stops working when an endpoint is called (get/post). 

Could you please help me? Thanks in advance!

**Comment by bimalkjha** [comment]
@crishmc `.\node_modules\ibmmq\redist\gskit8\lib64` get installed when we install Db2 server in the system or install GSKit using gskit installer. So, what is the output of `db2level` when `.\node_modules\ibmmq\redist\gskit8\lib64` is effective? Your system should have `C:\Program Files\IBM\SQLLIB` directory. You can cd to SQLLIB\bin and then run `.\db2level` to know the exact output.
You can check the output of `.\db2level` from `..\node_modules\ibm_db\installer\clidriver\bin` directory too. Due to the difference in the GSKit lib of these two installations, issue comes.
I think the endpoint call will use the dll from the `C:\Program Files\IBM\SQLLIB\bin` directory. Updating PATH to use single dll should work.
Please share output of below commands:
```
C:\Program Files\IBM\SQLLIB\bin\db2level
c:\xxxx\node_modules\ibm_db\installer\clidriver\bin\db2level
echo %PATH%
echo %LIB%
```
Thanks.

**Comment by crishmc** [comment]
Hello Bimal! 
My computer doesn't have the path C:\Program Files\IBM\SQLLIB\bin\db2level, so I have run the other commands. I just sent the result to your slack. Thanks!

**Comment by crishmc** [comment]
Hello, @bimalkjha Do you have any updates about this issue? Thanks

**Comment by bimalkjha** [comment]
@crishmc It seems `ibmmq`  has installed its own gskit library which is causing conflict with the gskit library that comes with `ibm_db` driver. At a time only one library can work. Please share the output of below commands:
```
db2cli validate
ls -l ..\node_modules\ibmmq\redist\gskit8\lib64
```
Also clarify that - for endpoint call, ibm_db is used or ibmmq is used?
 - for scheduled process, ibm_db is used or ibmmq?
 
Edit your System Environment variable and add `C:\Cris\Override SQUAD\Git\GitXBIS-Back\XBIS-Back\node_modules\ibm_db\installer\clidriver\bin\icc64` at the start of PATH and LIB environment variables and then test. Thanks.
