### ISSUE TITLE
empty error for conn.query when statement is like "select ID from final TABLE( INSERT INTO ..." and UNIQUE constraint error occurs 

### ISSUE THREAD

**Issue by meier297** [ibmdb/node-ibm_db#81]
It could happen, that my code will insert redundant data into my table, where a unique constraint exists. Fortunately the unique constraint forbids the inserting and an error occurs. When I want to analyze the error, I only get an empty error result. The error result is only empty when my SQL statement is like "select ID from **final** TABLE( INSERT INTO ..."

The empty error occurs with the following code:

    conn.query(query_stmt, function(err, sqlResult) {
        if (err) {
            console.log(err);	// {error: []}
        } else { 
    ...

the following code with the same query_stmt shows error details:

    conn.prepare(query_stmt, function (err, stmt) {
        if (err) {
            console.log(err);
        }
		 
        stmt.execute([], function (err, result) {
            if( err ) console.log(err);  // error.message: '[IBM][CLI Driver] ... One or more values in the insert statement ... are not valid because the ... unique constraint ...
        ...

Is there a right reason, why the first code ha an empty error  but in the second case not?

**Comment by bimalkjha** [comment]
Please share your test program to repro the issue. It would be easy for us to find the root cause. Thanks.

**Comment by qpresley** [comment]
Here is an example set of SQL statements to repro along with the output in the returned data field for each statement

>>> The create statement below creates a table with a generated primary key named ID that starts with 1 and increments by 1
sql="CREATE TABLE \"ProductTest\" (\n  \"name\" VARCHAR(512) NULL,\n  \"id\" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),\n  PRIMARY KEY(\"id\")\n)" params=[] err=null data=[] more=false

>>> The statement below inserts a row with primary key value of 1 that is generated as per the table definition.  The data field returns the ID that was inserted
sql="SELECT \"id\" FROM FINAL TABLE (INSERT INTO \"ProductTest\"(\"name\") VALUES((?)))" params=["a-name"] err=null data=[{"id":1}] more=false

>>> This statement is attempting to insert a primary key value of 1 which within DB2 will return SQL0803N as shown below which is a DB2 CLP executed set of statements.  This statement SHOULD return SQL0803N in the errors field but instead returns an empty result set.
sql="SELECT \"id\" FROM FINAL TABLE (INSERT INTO \"ProductTest\"(\"name\",\"id\") VALUES((?),(?)))" params=["duplicate",1] err={"errors":[]} data=[] more=undefined

>>> The following is the output from a DB2 CLP execution of the above statements

CREATE TABLE PRODUCTTEST (NAME VARCHAR(512) NULL, ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),  PRIMARY KEY(ID))
DB20000I  The SQL command completed successfully.

SELECT ID AS ID FROM FINAL TABLE (INSERT INTO PRODUCTTEST(NAME) VALUES('a-name'))

ID         
-----------
          1

  1 record(s) selected.


SELECT ID AS ID FROM FINAL TABLE (INSERT INTO PRODUCTTEST(NAME, ID) VALUES('duplicate',1))
SQL0803N  One or more values in the INSERT statement, UPDATE statement, or 
foreign key update caused by a DELETE statement are not valid because the 
primary key, unique constraint or unique index identified by "1" constrains 
table "<schema>.PRODUCTTEST" from having duplicate values for the index key.  
SQLSTATE=23505

DROP TABLE PRODUCTTEST
DB20000I  The SQL command completed successfully.

**Comment by bimalkjha** [comment]
@qpresley Thanks for sharing the repro. We are able to repro the issue and delivered fix for it. Please use this file https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js Thanks.

**Comment by bimalkjha** [comment]
Fix of this issue is released in v 0.0.18.
