### ISSUE TITLE
(CS2641234) SQL20570N  The statement failed because the number of rejected rows exceeds the limit set in the MaxErrors option value. SQLSTATE=22551 SQLCODE=-20570

### ISSUE THREAD

**Issue by reoawazu** [ibmdb/node-ibm_db#815]
(CS2641234)
I am using a Db2 warehouse on cloud, jupyter notebook  with Watson studio and objectstorage on same IBM cloud environment.
And I am sending a query from jupyter notebook to Db2 warehouse on cloud.

One day, when I stored some csv files in object storage and load these data to Db2, I met a SQL20570N error on only one table.
Other tables were no problem and data load successfully.

I'd like to resolve the error, but I can't check the reason of this issue.
Because when the error occured, jupyter notebook showed only the below messages.
<Error messages>
ibm_db_dbi::DataError: Statement Execute Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL20570N  The statement failed because the number of rejected rows exceeds the limit set in the MaxErrors option value. Log file name: "BLUDB.BLUADMIN.SYSTET38178.<table name>.csv.00061273.0000008.log".  SQLSTATE=22551 SQLCODE=-20570

<SQL (same with other tables)>
insert_query = "INSERT INTO " + load_table_name +" SELECT * FROM EXTERNAL " + "'" + load_file_name + "'"  + " USING \
  (CCSID 1208 s3('s3.ap.cloud-object-storage.appdomain.cloud',  \
  '" + db2_params['api_keys']['access_key'] + "', \
  '" + db2_params['api_keys']['secret_access_key'] + "', \
  '" + db2_params['api_keys']['bucket_name'] + "' \
     )DELIMITER ',' SKIPROWS 1 QUOTEDVALUE DOUBLE CTRLCHARS ON TIMESTAMP_FORMAT 'YYYY/MM/DD HH24.MI'\
  )"

How can I resolve this issue ?
Regards

**Comment by bimalkjha** [comment]
@reoawazu Check the user response section of this error message details here: https://www.ibm.com/docs/en/db2/11.5?topic=messages-sql20500-sql20999#sql20570n

**SQL20570N The statement failed because the number of rejected rows exceeds the limit set in the MaxErrors option value. Log file name: log-file-name.**
**Explanation**

The data for an external table is stored in a file that can be located locally or remotely.

The data in the file might not perfectly match the column definitions of the external table. When you select data from an external table, the database manager might need to alter or convert the data to enable the SELECT statement to return a result set. However, sometimes the data from a particular row of data cannot be altered or converted successfully. When that happens, the row is rejected and is not included in the result set.

You can use the MaxErrors external table option to specify a threshold for the number of rejected rows. When that threshold is exceeded, the attempt to process the SELECT statement is canceled.

This message is returned when a SELECT statement is issued for data in an external table and the attempt to process the statement fails because more rows have been rejected than the threshold set by the MaxErrors option.
**User response**

Address this error in one or more of the following ways:

    To reduce the number of rejected rows, alter the data in the file so that it matches the column definitions of the external table.
    To reduce the number of rejected rows, alter the column definitions of the external table so it better matches the data in the file.
    To allow the statement to be processed despite the mismatches between the column definitions of the external table and the data in the file, increase the value of the MaxErrors option.

**Comment by reoawazu** [comment]
@bimalkjha 
Thank you for your comment.
When I use escape character by python from jupyter notebook, it looked like not functionally.
So I used double quotaion for csv data, resolved this issue.

**Comment by vudoan31121990** [comment]
@bimalkjha : Hi Bimalkjha, I have the same issue above that I don't want to open new ticket for this because of duplication. So in the three ways of fixing errors, I don't know how we can do that. Can you help me to explain more clearly steps that I can follow to fix this issue?

**Comment by bimalkjha** [comment]
@This error happens due to mismatch in the data being inserted and corresponding column type in the table. So, you need to check column types of your table and see you are providing data in right format. f.e. If column type is integer but data being inserted is varchar, so data can't get inserted and rows will be rejected. Thanks.

**Comment by vudoan31121990** [comment]
@bimalkjha : When I run the query standalone directly in the db application, the query ran successfully. But when we run the query inside our application with ibm_db node library, it will give us this error.

**Comment by bimalkjha** [comment]
@vudoan31121990 What type of db application you are using? Is it SQL starting with "db2"  i.e. being executed by CLP or some JDBC/ODBC application?
If you can write a sample node.js test program to reproduce the issue, then replace the `db2cli validate` command in file `ibm_db\installer\testODBCConnection.sh[.bat]`  with `node test.js` and execute this script to collect db2trace. Share all generated 1.* file with test file here. We can check the db2 trace files to find the root cause. Thanks.

**Comment by vudoan31121990** [comment]
@bimalkjha : I used the BDeaver as the Universal Database Management application to run the query, and it ran successfully. I tried to follow your suggestion, but I dont understand what you mean to replace the db2cli validate command in the file. Can you explain clearly what I should do? Here is my index.js file that I tried to make to test.

[index.txt](https://github.com/ibmdb/node-ibm_db/files/9537070/index.txt)

**Comment by bimalkjha** [comment]
@vudoan31121990 BDeaver uses JDBC driver internally. I am not sure you installed ibm_db on which Operating System? So, if you open file `ibm_db\installer\testODBCConnection.sh` for non Windows and `ibm_db\installer\testODBCConnection.bat` for Windows, you can find a line starting with `db2cli validate` at line no 29 in testODBCConnection.sh (or at line no 16 in testODBCConnection.bat). You need to comment this line and add `node inext.js` just after it, so that you test program will get executed by this script. Then you can run this script.
Please share below details too:
1. Operating System name on which you installed ibm_db.
2. Node.js version.
3. Create table command for table BAIW_CONGA.CONTRACT_BASE_CONGA to know column types
4. File BAIW_CONGA.CONTRACT_BASE_CONGA_20220907.txt with few failing rows.
Thanks.

**Comment by vudoan31121990** [comment]
@bimalkjha : here is details below:
1. I am using Mac
2. Node version: V14.15.5
3. `CREATE TABLE "BAIW_CONGA"."CONTRACT_BASE_CONGA"  (
		  "PLATFORM_NAME" VARCHAR(60 OCTETS) , 
		  "PRODUCT_DESCRIPTION" VARCHAR(255 OCTETS) , 
		  "MACHINE_TYPE" VARCHAR(50 OCTETS) NOT NULL , 
		  "MACHINE_MODEL" VARCHAR(50 OCTETS) NOT NULL , 
		  "SERIAL_NUMBER" VARCHAR(50 OCTETS) , 
		  "SERIAL_NUM5" VARCHAR(50 OCTETS) , 
		  "CONTRACT_NO" VARCHAR(50 OCTETS) , 
		  "CONTRACT_START_DATE" DATE , 
		  "CONTRACT_END_DATE" DATE , 
		  "CONTRACT_DUR" INTEGER , 
		  "SERVICE_TYPE" VARCHAR(14 OCTETS) NOT NULL , 
		  "SERVICE_NM" VARCHAR(255 OCTETS) , 
		  "SERVICE_LVL" VARCHAR(255 OCTETS) , 
		  "CUSTOMER_NUMBER" VARCHAR(8 OCTETS) NOT NULL , 
		  "CUSTOMER_NAME" VARCHAR(142 OCTETS) , 
		  "COUNTRY" VARCHAR(38 OCTETS) , 
		  "REGION_NAME" VARCHAR(255 OCTETS) , 
		  "GEO_NAME" VARCHAR(255 OCTETS) , 
		  "COMP_STATUS" VARCHAR(10 OCTETS) , 
		  "COMP_TOT_AMT_USD" DOUBLE , 
		  "CONTR_TOT_AMT_USD" DOUBLE , 
		  "COMP_TOT_AMT_LCL" DOUBLE , 
		  "CONTR_TOT_AMT_LCL" DOUBLE , 
		  "COMP_SEQ_NUMBER" INTEGER , 
		  "SOURCE_CODE" VARCHAR(3 OCTETS) NOT NULL , 
		  "COMP_START_DATE" DATE , 
		  "COMP_STOP_DATE" DATE , 
		  "COMP_MAINT_CHARGE" VARCHAR(1 OCTETS) , 
		  "COMP_MAINT_PERIOD" VARCHAR(1 OCTETS) , 
		  "CONTR_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "OFFERING_ID" VARCHAR(8 OCTETS) , 
		  "OFFERING_VER" VARCHAR(11 OCTETS) NOT NULL , 
		  "FF_CHNL" VARCHAR(50 OCTETS) , 
		  "FF_CHNL_DESC" VARCHAR(128 OCTETS) NOT NULL , 
		  "DIVISION_CODE" VARCHAR(2 OCTETS) , 
		  "PRODUCT_KEY" INTEGER , 
		  "COUNTRY_KEY" INTEGER , 
		  "CNTRY_CD" VARCHAR(32 OCTETS) , 
		  "CONTR_CNTRY_NAME" VARCHAR(255 OCTETS) , 
		  "CUST_CNTRY_ISO2" VARCHAR(38 OCTETS) , 
		  "CUST_CNTRY_NAME" VARCHAR(255 OCTETS) , 
		  "CUST_NO_10" VARCHAR(10 OCTETS) NOT NULL , 
		  "CURR_CODE" VARCHAR(6 OCTETS) , 
		  "TERM_COMM_PRD" VARCHAR(2 OCTETS) , 
		  "PRICE_PROTECTED" VARCHAR(1 OCTETS) , 
		  "CUST_LOC" VARCHAR(208 OCTETS) NOT NULL , 
		  "BILL_CUST_NO" VARCHAR(8 OCTETS) NOT NULL , 
		  "BILL_CUST_NO_10" VARCHAR(10 OCTETS) NOT NULL , 
		  "BILL_CUST_NAME" VARCHAR(200 OCTETS) NOT NULL , 
		  "INST_CUST_NO" VARCHAR(8 OCTETS) NOT NULL , 
		  "INST_CUST_NO_10" VARCHAR(10 OCTETS) NOT NULL , 
		  "INST_CUST_NAME" VARCHAR(200 OCTETS) NOT NULL , 
		  "SIGN_CUST_NO" VARCHAR(8 OCTETS) NOT NULL , 
		  "SIGN_CUST_NO_10" VARCHAR(10 OCTETS) NOT NULL , 
		  "SIGN_CUST_NAME" VARCHAR(200 OCTETS) NOT NULL , 
		  "CONTR_PER_END_DATE" DATE , 
		  "COMP_PER_END_DATE" DATE , 
		  "BTM_LINE_IND" VARCHAR(1 OCTETS) NOT NULL , 
		  "OFFER_CAT_CD" VARCHAR(8 OCTETS) , 
		  "CONTR_TOT_AMT_USD_REV" DECIMAL(20,2) , 
		  "COMP_TOT_AMT_USD_REV" DECIMAL(20,2) , 
		  "LCL2USD_EXRATE" DECIMAL(31,2) , 
		  "BILL_FREQ" VARCHAR(2 OCTETS) , 
		  "PREPAY_IND" VARCHAR(1 OCTETS) NOT NULL , 
		  "STOP_REASON_CODE" VARCHAR(1 OCTETS) , 
		  "OFFERING_ID_NORM" VARCHAR(128 OCTETS) NOT NULL , 
		  "SL_CD" VARCHAR(50 OCTETS) , 
		  "SERIAL_SEVEN" VARCHAR(50 OCTETS) , 
		  "DAILY_VALUE_USD" DOUBLE , 
		  "DAILY_VALUE_LCL" DOUBLE , 
		  "DS_FROM" VARCHAR(5 OCTETS) NOT NULL , 
		  "DISTRIBUTOR_CEID" VARCHAR(22 OCTETS) , 
		  "DISTRIBUTOR_NAME" VARCHAR(142 OCTETS) , 
		  "DISTRIBUTOR_CUST_NO" VARCHAR(8 OCTETS) , 
		  "AGENT_ID" VARCHAR(22 OCTETS) , 
		  "AGENT_ID_NORM" VARCHAR(22 OCTETS) , 
		  "BUSINESS_PARTNER_CEID" VARCHAR(22 OCTETS) , 
		  "BUSINESS_PARTNER_NAME" VARCHAR(142 OCTETS) , 
		  "BUSINESS_PARTNER_CMR" VARCHAR(32 OCTETS) , 
		  "BUSINESS_PARTNER_CUSTNO" VARCHAR(8 OCTETS) , 
		  "POC_COUNTRY_CD" VARCHAR(20 OCTETS) , 
		  "POC_EMAIL_ID" VARCHAR(255 OCTETS) , 
		  "POC_FIRST_NAME" VARCHAR(255 OCTETS) , 
		  "POC_LAST_NAME" VARCHAR(255 OCTETS) , 
		  "POC_PHONE_NUM" VARCHAR(20 OCTETS) , 
		  "TCP_MONTH" INTEGER NOT NULL , 
		  "COMP_END_NORM" DATE , 
		  "CONTR_END_NORM" DATE , 
		  "SERIAL_KEY" VARCHAR(86 OCTETS) , 
		  "SERIAL_KEY5" VARCHAR(86 OCTETS) , 
		  "BRAND" VARCHAR(128 OCTETS) NOT NULL , 
		  "BRAND_BY_SN" VARCHAR(128 OCTETS) , 
		  "SUBBRAND" VARCHAR(30 OCTETS) , 
		  "SERV_NM_CAT" VARCHAR(255 OCTETS) , 
		  "EOS_DATE" DATE , 
		  "EOS_FLAG" VARCHAR(1 OCTETS) NOT NULL , 
		  "EXCLUDED_FROM_SERVER_COUNT" CHAR(1 OCTETS) , 
		  "PROD_CATE" CHAR(1 OCTETS) , 
		  "MANUFACTURER" VARCHAR(64 OCTETS) , 
		  "GEO" VARCHAR(3 OCTETS) NOT NULL , 
		  "COMP_STOP_DATE_NORM" DATE , 
		  "SERIAL_NORM" VARCHAR(50 OCTETS) , 
		  "OFFR_IN_SCOPE" VARCHAR(1 OCTETS) NOT NULL , 
		  "ASF_GRP" VARCHAR(6 OCTETS) NOT NULL , 
		  "SERIAL_KEY_NORM" VARCHAR(86 OCTETS) , 
		  "SEQ_ASF_FLAG" VARCHAR(1 OCTETS) , 
		  "ASF_FLG_LATEST" VARCHAR(1 OCTETS) , 
		  "SERVICEPAC_FLG" VARCHAR(1 OCTETS) , 
		  "BMCCO_OFFERING_ID_L40" VARCHAR(8 OCTETS) , 
		  "COMPONENT_KEY" VARCHAR(278 OCTETS) , 
		  "CONTR_DAYS" INTEGER , 
		  "COMP_DAYS" INTEGER , 
		  "TERM" INTEGER , 
		  "AUTO_RENEWAL_FLG" CHAR(1 OCTETS) , 
		  "TC_NBR" VARCHAR(1 OCTETS) , 
		  "TC_DESC" VARCHAR(1 OCTETS) , 
		  "CONTR_ACCPTN_DATE" DATE , 
		  "AGRMT_ACTVN_DATE" DATE , 
		  "CUST_SIGN_DATE" VARCHAR(1 OCTETS) , 
		  "TERM_START_DATE" DATE , 
		  "TERM_END_DATE" DATE , 
		  "CONTR_PER_START_DATE" VARCHAR(1 OCTETS) , 
		  "CONTR_PER_STOP_DATE" VARCHAR(1 OCTETS) , 
		  "SB_ID" VARCHAR(1 OCTETS) , 
		  "SB_EFFECT_DATE" VARCHAR(1 OCTETS) , 
		  "SB_EXPIRE_DATE" VARCHAR(1 OCTETS) , 
		  "TERM_NUMBER" VARCHAR(2 OCTETS) , 
		  "SPEC_BID_LEVEL" VARCHAR(1 OCTETS) , 
		  "SB_ADJ_PERCENT" DOUBLE , 
		  "SB_PERCENT" DOUBLE , 
		  "TOTAL_DISC_PCT" DOUBLE , 
		  "LIO_CREATE_DATE" DATE , 
		  "ASSET_LI_DESC" VARCHAR(255 OCTETS) , 
		  "L30_CODE" VARCHAR(8 OCTETS) , 
		  "L30_NAME" VARCHAR(255 OCTETS) , 
		  "L40_CODE" VARCHAR(8 OCTETS) , 
		  "L40_NAME" VARCHAR(255 OCTETS) , 
		  "BASE_PRICE" DOUBLE , 
		  "NET_PRICE" DOUBLE , 
		  "BP_NET_PRICE" DOUBLE NOT NULL , 
		  "EXTENDED_COST" DOUBLE , 
		  "NET_ADJUSTMENT" DOUBLE , 
		  "BP_ADJUSTMENT" DOUBLE , 
		  "TOTAL_ADJUSTMENT" DOUBLE , 
		  "SB_MODE_INDC" VARCHAR(1 OCTETS) NOT NULL , 
		  "SB_DEF_TYPE_ADJ" VARCHAR(1 OCTETS) , 
		  "CONTRACT_BASE_PRICE" DOUBLE , 
		  "CONTRACT_NET_PRICE" DOUBLE , 
		  "CONTRACT_BP_NET_PRICE" DOUBLE , 
		  "CONTRACT_NET_ADJUSTMENT" DOUBLE , 
		  "CONTRACT_BP_ADJUSTMENT" DOUBLE , 
		  "CONTRACT_TOTAL_ADJUSTMENT" DOUBLE , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "SERVICE_LVL_CODE" VARCHAR(100 OCTETS) )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW;`

4. Here is the file with one row data

[BAIW_CONGA.CONTRACT_BASE_CONGA_20220907.txt](https://github.com/ibmdb/node-ibm_db/files/9538601/BAIW_CONGA.CONTRACT_BASE_CONGA_20220907.txt)
