### ISSUE TITLE
SSLServerCertificate doubt

### ISSUE THREAD

**Issue by betogm08** [ibmdb/node-ibm_db#827]
Hi! I have a question. Is it possible to pass in SSLServerCertificate the certificate as string instead of path to the .arm file?

**Comment by betogm08** [comment]
Also, wondering if it is possible to pass a remote path?

**Comment by bimalkjha** [comment]
@betogm08 `ibm_db` driver accepts connection string in IBM ODBC Driver format and submits the connection string as it is to clidriver. The keyword and corresponding value with way of use is documented here: https://www.ibm.com/docs/en/db2/11.5?topic=cck-sslservercertificate
Unless, IBM ODBC/CLI Driver support different format for SSLServerCertificate, ibm_db can not support that. 
So, the format must be `SSLServerCertificate = "<fully_qualified_certificate_name>"` as per documentation. You can not use a remote path.

If you don't want to use this format, then you can create a keystoredb using GSKit on client system, add certificate to this keystoredb and use `SSLClientKeystoredb` and `SSLClientKeyStoreDBPassword/SSLClientKeystash` keyword in connection string instead of SSLServerCertificate keyword as `"Database=sampledb; Protocol=tcpip; Hostname= myhost; Servicename=50001; 
Security=ssl; SSLClientKeystoredb=/home/test1/keystore/clientstore.kdb;
SSLClientKeystash=/home/test1/keystore/clientstore.sth;"`. Detail steps are documented [here](https://www.ibm.com/docs/en/db2/11.5?topic=ctsidc-configuring-tls-support-in-non-java-db2-clients). Thanks.

**Comment by betogm08** [comment]
@bimalkjha This is part of the documentation: "The SSLServerCertificate keyword is not required if the certificate that is required to establish an SSL connection is already stored in the keystore database."

This means that if I store the cetificate in the key store database, The connection will be established without SSLServerCertificate? If yes, how can I store the certificate?

**Comment by betogm08** [comment]
The problem to use SSLServerCertificate is to have certificate.arm as part of the repository and github. As I understand, that would be a security issue.

**Comment by bimalkjha** [comment]
@betogm08 You can store certificate in keystoredb created using GSKit. To avoid use of SSLServerCertificate keyword, you need to install "IBM Global Security Toolkit" aka GSKit on your system, create keystoredb and add server certificate to it. I have shared link with detail info in my previous update. You can find more info here: https://www.ibm.com/docs/en/db2/11.5?topic=ctsidc-configuring-tls-support-in-non-java-db2-clients
Also, if you are connecting to Db2 in Cloud i.e. a BLUDB, then no need to use SSLServerCertificate and no need to use GSKit. Thanks.
