### ISSUE TITLE
[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL"

### ISSUE THREAD

**Issue by iprasla** [ibmdb/node-ibm_db#828]
I am noticing this error in our microservice when it is trying to make a connection to db2.

```
error: Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "420", "*", "*".  SQLSTATE=08001
  
      at Database.openSync (/home/module/app/node_modules/ibm_db/lib/odbc.js:413:26)
      at Function.module.exports.openSync (/home/module/app/node_modules/ibm_db/lib/odbc.js:149:6)
 error: '[ibm_db] SQL_ERROR',
    sqlcode: -30081,
    state: '08001'
```
The microservice is hosted on IBM cloud pipeline and the microservice is using ibm_db node module package. The connection string looks like the one below:
```
const Conn='DATABASE=<DB>;HOSTNAME=<hostname>;PORT=50001;PROTOCOL=TCPIP;UID=<UID>;PWD=<PWD>;Security=SSL';
```

**Comment by bimalkjha** [comment]
@iprasla In the error details of SQL30081N error, we can see the protocol specific error code is 420 which means "420 – The partner closed the socket before the protocol completed."
There can be multiple reasons for this error:
1. The connection was open and idle since long time, so server has closed the connection due to connection timeout set on server.
2. The network has some issue which caused broken connection.
If you see this issue frequently, check your application logic and avoid idle connection.
If you are using pooled connections, either handle this error in the code or configure db2dsdriver.cfg file to reconnect seamlessly when this error get encountered by the application.

This issue looks duplicate of issues 808 and 810. So, please check those issues for solution. We have documented about this problem here: https://github.com/ibmdb/node-ibm_db#getting-sql30081n-error--occasionally-after-some-time-of-inactivity--check-issue810
Thanks.

**Comment by iprasla** [comment]
I read through the link posted but it appears this addresses to intermittent connection failure. On my end it is consistently throwing that error without connecting. This seems to work locally but doesn't work in a cluster. The cluster where the app is hosted has istio proxy (allow list) to filter the external connections. Is that something that can cause connection issue?

**Comment by bimalkjha** [comment]
@iprasla Yes, the proxy settings could block the connection. Please add the target host in the known host list. Thanks.

**Comment by bimalkjha** [comment]
@iprasla Are you still facing this issue after correcting the proxy settings? Please update. Thanks.

**Comment by iprasla** [comment]
The db2 server is hosted on the cloud. The microservice that talks to db2 is on a cluster that I do not have access to. From local machine I can connect to db2 perfectly fine. I am not sure how to connect to db2 server from the cluster. Is there a curl command do that?

**Comment by iprasla** [comment]
When I run the following command
```
./db2cli execsql -connstring "DATABASE=<DB>;HOSTNAME=<hostname>;PORT=50001;PROTOCOL=TCPIP;UID=<UID>;PWD=<PWD>;Security=SSL"
```
I get this response which is unusual because I know the password is not expired and I can query data locally:
```
IBM DATABASE 2 Interactive CLI Sample Program
(C) COPYRIGHT International Business Machines Corp. 1993,1996
All Rights Reserved
Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
SQLError: rc = 0 (SQL_SUCCESS) 
SQLGetDiagRec: SQLState     : 08001
          fNativeError : -30082
          szErrorMsg   : [IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=08001

          cbErrorMsg   : 127
```

**Comment by bimalkjha** [comment]
@iprasla Please join meeting here: https://rocketsoftware.webex.com/meet/bjha

**Comment by bimalkjha** [comment]
@iprasla If you are not joining the meeting in 10min then, please join after 12hrs and click on notify host button. I'll join. Thanks.

**Comment by iprasla** [comment]
> @iprasla Please join meeting here: https://rocketsoftware.webex.com/meet/bjha

I am waiting.

**Comment by iprasla** [comment]
Closing issues as the problem lies with the cluster configuration.
