### ISSUE TITLE
outdate library dependency with grpc@1.24.9

### ISSUE THREAD

**Issue by dilas12345** [ibmdb/node-ibm_db#855]
Hi,

I have been trying to install the the node-ibm_db library but for some reasons it kept flagging an error with grpc@1.24.9 deprication and and need some upgrade to @grpc/grpc-js.

This is causing a lot of issues with the library insallation using "npm install ibm_db
![Screenshot from 2022-05-24 18-04-26](https://user-images.githubusercontent.com/7136370/170140204-a22f8d31-29ba-4106-82dd-c6887c659379.png)
"

**Comment by bimalkjha** [comment]
@dilas12345 What is your node.js version and Operating System name on which you are trying to install ibm_db? Thanks.

**Comment by dilas12345** [comment]
My Operating system version is Ubuntu 20.04 and node version V16.15.0

**Comment by bimalkjha** [comment]
@dilas12345 The error that you are facing is not due to deprecation warning of code-js or grpc. But it is due to npm fails to login due to incorrect or missing output. npm gives warning about grpc and not the error. If you have registered on npmjs.org, just run "npm login" and provide the correct password, that should resolve the issue.

Regarding installation on Ubuntu, I tried installing and it installs without any error. Please see the below results:
```
bjha@waldevdbcttst07: bjha/nodework/installed> cat /etc/issue
Ubuntu 20.04 LTS \n \l

bjha@waldevdbcttst07: bjha/nodework/installed> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
bjha@waldevdbcttst07: bjha/nodework/installed> npm install ibm_db

added 60 packages, and audited 61 packages in 13s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Please check the log file under /home/dilas/.npm/_logs/ for more details.
Thanks.

**Comment by dilas12345** [comment]
Yes, please do.
