### ISSUE TITLE
Connection lost   after few days of inactivity

### ISSUE THREAD

**Issue by zamrokk** [ibmdb/node-ibm_db#86]
I am using      ibmdb.open     on an application with the Bluemix platform.
Then i realized that after few days of inactivity, the connection cannot open anymore. I have to restart the application. I guess the database has restarted somehow.

Is there any solution the reestablish the connection without restarting the application on the Bluemix console ?

**Comment by bimalkjha** [comment]
Use connection pooling methods offered by ibm_db. Use pool.open instead of ibmdb.open. Btw, why are you keeping opened connection idle. It might be programming problem with your application. After use, call ibm_db.close to close the connection. Better to use pooling, get a connection from pool and after use return the connection back to pool. thanks.

**Comment by zamrokk** [comment]
i was properly closing connection.

I will try the pool feature to see the difference. 

but something weird on line 818 of odbc.js, why the callback function is mandatory when calling db.close ?
    db.close = function (cb) 
    {
    //call back early, we can do the rest of this stuff after the client 
    //thinks that the connection is closed.
    cb(null);

**Comment by rhtpandeyIN** [comment]
Hi @zamrokk ,

callback function is mandatory here because before actually closing the db connection it does following things:

1-->   If this connection has some active transaction,then it rollback the
        transaction to free up the held resources before moving back to
        the pool. So that, next request can get a fresh connection from pool.
     
 if(db.conn && db.conn.inTransaction)
      {
          db.rollbackTransaction(function(err){});
      }

2--> after that it removes this db from the usedPool
     
      self.usedPool[connStr].splice(self.usedPool[connStr].indexOf(db), 1);

3-->  move this connection back to the connection pool
      if(db.conn)
      {
        self.availablePool[connStr] = self.availablePool[connStr] || [];
        self.availablePool[connStr].push(db);
      }
      exports.debug && console.dir(self);
    }; 

4--> and then db will be closed properly.

**Comment by rhtpandeyIN** [comment]
Hi @zamrokk,

are you still facing an issue with Connection, do let us know, we'll look into it.
Thanks.

**Comment by zamrokk** [comment]
Last restart was monday. I use the pool now and i still not have any problem.
Tell you informed

**Comment by rhtpandeyIN** [comment]
Thanks @zamrokk , I am closing the issue now.
