### ISSUE TITLE
Getting 403 Forbidden access issue while trying to download ibm db CLI for Mac

### ISSUE THREAD

**Issue by Hari1001** [ibmdb/node-ibm_db#933]
<img width="1440" alt="image" src="https://github.com/ibmdb/node-ibm_db/assets/20398011/eb687809-a896-40a8-ad43-54f4542f3a22">

**Comment by bimalkjha** [comment]
@Hari1001 There seems some issue with https://public.dhe.ibm.com due to weekend lab maintenance activity. I have informed the contact who maintains this site. We also started saving the replica of it on github, so if you want, you may download it from https://github.com/ibmdb/db2drivers/tree/main/clidriver. Thanks.

**Comment by bimalkjha** [comment]
The site is up now and clidriver is available for download. Thanks.
