### ISSUE TITLE
Getting 403 Forbidden access issue while trying to download ibm db CLI for Linux

### ISSUE THREAD

**Issue by ljerka** [ibmdb/node-ibm_db#934]
Getting an error while doing npm install:

Error 403: Forbidden - https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz

It seems to be a newer issue. Few days ago I could install it without a problem. I noticed this today.

**Comment by bimalkjha** [comment]
There seems some issue with https://public.dhe.ibm.com/ due to weekend lab maintenance activity. I have informed the contact who maintains this site. We also started saving the replica of it on github, so if you want, you may download it from https://github.com/ibmdb/db2drivers/tree/main/clidriver. Thanks.
