### ISSUE TITLE
queryResult deferred callback result changed with version 3.2.3

### ISSUE THREAD

**Issue by Stoyz** [ibmdb/node-ibm_db#979]
Hello,
I am opening this issue to ask a question about the PR #953 (merged and published in version 3.2.3) which changes the deferred resolve of the `queryResult` function to an array as you can see in [this comparison](https://github.com/ibmdb/node-ibm_db/commit/ceafbb5afa2abc1ab75104e2d298587fca072c58?diff=unified&w=0#diff-920cb7594b20769ba515da5afaa62ec0c2c843b74dde86468207dd7db48bbf42R764).

Has the change been intentional? If so, do you mind if I ask why the change has not been marked as breaking change?

I have a piece of code which does not work anymore due to the change and I had to take the first value of the array in order to use the `getAffectedRowsSync` function.

Follows a portion of the code I am now using:
```js
const result = await connection.queryResult(sql, params);

// the following line used to be: const affectedRows = result.getAffectedRowsSync();
const affectedRows = result[0].getAffectedRowsSync();
```

Thank you.

**Comment by bimalkjha** [comment]
@Stoyz I think  you are pointing about below change in PR:
![image](https://github.com/ibmdb/node-ibm_db/assets/11818648/57304ad5-4c4b-4440-9d67-0dd8135ad0d9)

This change has fixed a bug in the queryResult() API. `await result= conn.queryResult()` do not return `outparams` for Stored Procedure call with OUTPUT or INOUT type of parameters, when async-await programming is used. So, we are resolving the promise as an array and data can be extracted from the array by application. We found this bug in the code while fixing other issues. So, the change is intentional as a bug fix. Hope, it clarifies. Thanks.

**Comment by Stoyz** [comment]
Thank you for the clarification @bimalkjha

Only thing, in my opinion, this change should've been marked as breaking because it broke my code and there was no mention about this.

**Comment by bimalkjha** [comment]
@Stoyz I agree, but I am not sure about how to mark about it. Could you please help me with your suggestion about the steps or place to mention about it? We'll try to follow it. Thanks.

**Comment by bimalkjha** [comment]
Thanks @Stoyz . Will update Changes.md in future breaking changes accordingly and do major release. Thanks.
