### ISSUE TITLE
Connection Pooling not working as expected .maxpool and settimeout having issue

### ISSUE THREAD

**Issue by jptech8** [ibmdb/node-ibm_db#987]
I could see below works well but when i set setMaxPoolSize and connectTimeout , it is not working as expect . I can see poo.init() manages all conenction request but maxpool not managing the request based o load . Could you help and have connection pooling working and establish conenction when it has high and connection close managed properly without explicity mentioning conn.close() ?

const ibmdb = require('ibm_db');
const connectionString = `DATABASE=your_database;HOSTNAME=your_hostname;PORT=your_port;PROTOCOL=TCPIP;UID=your_username;PWD=your_password`;
const pool = new ibmdb.Pool();
pool.init(2 connectionString)
pool.setMaxPoolSize(5, connectionString)
pool.setConnectTimeout(30, connectionString)
const db2 =()=>{
pool.open(connectionString, function( err, conn) {
return new Promise(async(resolve,reject)=>{
    try { 
if(err){console.log(error)}
resolve(conn)
     
    conn.close()
}catch(error){console.log(error)}
})
}
db2().then((conn)=>{conn.query(SELECT * FROM TABLE)})

**Comment by jptech8** [comment]
@bimalkjha , Thanks for the headsup .

Let me explain how i did testing Mssql and IBMdb2 might give an idea about load test . 

MSSQL  with connection pool {min:1,max:10} 

#I did load test and able to see min 1 of connection established and increased request load to 5000 concurrent request .
Result :- Could see result all 10 (max) established and released close connection back to pool with nestat tools command in my pods nestat -an


IBMDB2 with connection pool {poolSize:3,maxPoolSize:10}

#I did load test and able to see min 3 of connection established as PoolSize is locked as 3 and increased request load to 5000 concurrent request
Result :- Could see still same poolSize 3 established and no increase of established connection not more than 3 with same netstat tools command in my pods nestat -an


By this way , i assume IBMDB2 eventhough we set maxPoolSize to 10 , it is not gradually increased its established or TIMEWAIT to 10 . It still uses PoolSize =3 established connction unlike MSSQL uses connection pooling .

i used {idleTimeout autoCleanIdle} as suggested . Anyother way to check how IBMDB2 library could help to test maxpoolsize is used with 5000 concurrent request ?

**Comment by bimalkjha** [comment]
@jptech8 If we check the [this code](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L2589) of Pool() constructor, we can see that only `idleTimeout, autoCleanIdle, maxPoolSize, connectTimeout and systemNaming` keywrods are read from the options object passed to `new ibmdb.Pool({})`. so `poolSize:3` passed in pool option get ignored by ibm_db.

The maxPoolSize value can be set using pool.setMaxPoolSize (10) too and it do not change automatically. It is documented here: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-7-setmaxpoolsizen

You see 3 connections due to call of `pool.init(3,Db2Config)`. If you are firing 5000 concurrent connection requests, all requests(4990) might be hanging as maxpoolsize is 10. Please do not do that. ibm_db can make more than 128 concurrent connections as it allocates new connection handle for each connection and Db2 ODBC driver can have only 128 connection handles under an environment handle. So, we do not recommend to set maxpoolsize value >= 128. Also, simultaneous connection requests get queue and established one by one. That's why we recommend to use pool. You can test using a connection request of <=10 and then check. You can see it is growing after some time as actual connection takes some time.

You can update database connection info in file `ibm_db\test\config.json` and then run `node test\test-max-pool-size.js` to verify the maxPoolSize. 

To see the actual contents of pool and how it is growing, you can enable ibm_db logs by calling [ibmdb.debug(true)](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-38-debugvalue) function at start of your application. It will print lots of log on console.
Thanks.

**Comment by bimalkjha** [comment]
@jptech8 Any update about this issue? Thanks.

**Comment by jptech8** [comment]
I don't see gradual increase of connection in nestat . however i set the connection pooling as suggested . Hoping this should take more concurrent request and awaiting results from actual usuage .  Please close the call .Thanks  for the help
