### ISSUE TITLE
[IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

### ISSUE THREAD

**Issue by breno404** [ibmdb/node-ibm_db#992]
I'm work with a DB2 instance and I connect with this:
- connection_url = jdbc:db2://[cloud_url]:[port]/[database]:retrieveMessagesFromServerOnGetMessage=true;sslConnection=true;
- username = [username]
- password = [password]

I don't provide a .crt file, so I trying connect by node using this <code>connStr</code>
<code>"DATABASE=[database];HOSTNAME=[cloud_url];UID=[username];PWD=[password];PORT=[port];PROTOCOL=TCPIP;SECURITY=SSL"</code>

Where am I going wrong?

<b>Note</b>: I have the cli_driver configurated in my computer.
![image](https://github.com/ibmdb/node-ibm_db/assets/48841329/1578cefa-e2ba-45b2-bac4-ac7032141d53)

**Comment by bimalkjha** [comment]
@breno404 Your connStr is fine, but issue is with clidriver which seems older. It seems your system has multiple copies of db2 client/server installation and GSKit is installed at global path. First, please share complete output of below commands:
```
db2level
db2cli validate
node -v
npm install ibm_db
```
Thanks.

**Comment by bimalkjha** [comment]
SQL1042C error comes, due to problem in loading GSKit library. ibm_db addon binary may be compiled using different clidriver version and at runtime different clidriver is getting used. You should replace your existing clidriver with this one: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
Then try connection. If still fails, share complete output of above commands in previous post. Thanks.

**Comment by breno404** [comment]
<code>./db2level</code>
![image](https://github.com/ibmdb/node-ibm_db/assets/48841329/39d11351-f4c6-4a43-8d66-e7a0ed6f2652)

<code>./db2cli validate</code>
![image](https://github.com/ibmdb/node-ibm_db/assets/48841329/32055189-76b6-4f7c-ba8c-c225fb923af2)

<code>node -v</code>
![image](https://github.com/ibmdb/node-ibm_db/assets/48841329/c2f3d464-ef21-47ed-aa5f-f8e5f6fb6a79)

<code>npm install ibm_db</code>
command runned into /c/IBMDB2/CLIDRIVER/bin
![image](https://github.com/ibmdb/node-ibm_db/assets/48841329/780d288b-7a1e-4c09-9786-81307d36b7be)

**Comment by breno404** [comment]
![image](https://github.com/ibmdb/node-ibm_db/assets/48841329/6ee2c8bf-8ace-4e4c-bd9f-79a613b544a1)

**Comment by bimalkjha** [comment]
@breno404 Your system has clidriver of version 11.5.4.0 which is an old version and the gskit library that comes with this version of clidriver has many security vulnerabilities. Have you set system level environment variable IBM_DB_HOME=C:\IBMDB2\CLIDRIVER ? Please share output of `echo %IBM_DB_HOME% from command windows.

Do you see a clidriver directory under `...\node_modules\ibm_db\installer` directory after installation of ibm_db? If yes, then you need to set path of this clidriver in PATH and LIB environment variable to be effective. Please share contents of ibm_db\installer directory and full path of ibm_db directory. Thanks.

**Comment by bimalkjha** [comment]
If you get directory `...\node_modules\ibm_db\installer\clidriver` post installation of ibm_db, then run below commands from command windows:
```
cd ...\node_modules\ibm_db\installer\clidriver\scripts
setenv.bat
db2cli validate
node <your test program>.js
```
Alternatively, if you download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip, unzip it and replace your existing `C:\IBMDB2\CLIDRIVER` with this downloaded clidriver, your issue should get fixed. You are getting SQL1042C error due to old version of clidriver. Thanks.
